; Generated by KBCC
.stabs "KBCC",0x3c,0,0,0
.stabs "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\UsbMassStoragev_TSD",0x64,0,3,Ltext0
.stabs "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\AP4\sio\com.c",0x64,0,3,Ltext0

.area _$com_c$(ROM,REL)
Ltext0:
.stabs "int:t1=r1;-32768;32767;",128,0,0,0
.stabs "char:t2=r2;-128;127;",128,0,0,0
.stabs "double:t3=r1;8;0;",128,0,0,0
.stabs "float:t4=r1;4;0;",128,0,0,0
.stabs "long double:t5=r1;8;0;",128,0,0,0
.stabs "long int:t6=r1;-2147483648;2147483647;",128,0,0,0
.stabs "long long int:t7=r1;-2147483648;2147483647;",128,0,0,0
.stabs "short:t8=r1;-32768;32767;",128,0,0,0
.stabs "signed char:t9=r1;-128;127;",128,0,0,0
.stabs "unsigned char:t10=r1;0;255;",128,0,0,0
.stabs "unsigned long:t11=r1;0;4294967295;",128,0,0,0
.stabs "unsigned long long:t12=r1;0;4294967295;",128,0,0,0
.stabs "unsigned short:t13=r1;0;65535;",128,0,0,0
.stabs "unsigned int:t14=r1;0;65535;",128,0,0,0
.stabs "void:t15=15",128,0,0,0
.stabs "short __fixed:t16=r1;2;0;",128,0,0,0
.stabs "__fixed:t17=r1;2;0;",128,0,0,0
.stabs "long __fixed:t18=r1;4;0;",128,0,0,0
.stabs "unsigned short __fixed:t19=r1;2;0;",128,0,0,0
.stabs "unsigned __fixed:t20=r1;2;0;",128,0,0,0
.stabs "unsigned long __fixed:t21=r1;4;0;",128,0,0,0
.stabs "__sat short __fixed:t22=r1;2;0;",128,0,0,0
.stabs "__sat __fixed:t23=r1;2;0;",128,0,0,0
.stabs "__sat long __fixed:t24=r1;4;0;",128,0,0,0
.stabs "__sat unsigned short __fixed:t25=r1;2;0;",128,0,0,0
.stabs "__sat unsigned __fixed:t26=r1;2;0;",128,0,0,0
.stabs "__sat unsigned long __fixed:t27=r1;4;0;",128,0,0,0
.stabs "short __accum:t28=r1;4;0;",128,0,0,0
.stabs "__accum:t29=r1;4;0;",128,0,0,0
.stabs "long __accum:t30=r1;6;0;",128,0,0,0
.stabs "unsigned short __accum:t31=r1;4;0;",128,0,0,0
.stabs "unsigned __accum:t32=r1;4;0;",128,0,0,0
.stabs "unsigned long __accum:t33=r1;6;0;",128,0,0,0
.include "kbccmacro.asm"
 .define _sdtl_mount	 _sd1_mount        
 .define _sdtl_resv_size	 _sd1_res_size     
 .define _sdtl_get_size	 _sd1_fat_size     
 .define _sdtl_resv_read	 _sd1_res_read     
 .define _sdtl_resv_write	 _sd1_res_write    
 .define _sdtl_read	 _sd1_read         
 .define _sdtl_write	 _sd1_write        
 .define _sdtl_cache_init	 _sd1_cache2k_init 
 .define _sdtl_cache_read	 _sd1_cache_read   
 .define _sdtl_cache_write _sd1_cache_write  
 .define _sdtl_cache_flush _sd1_cache_flush  
 .define _sdtl_allocate    _sd1_allocate     
 .define _spif_res_size	 _spif_resv_size   
 .define _spif_res_read	 _spif_resv_read   
 .define _spif_res_write	 _spif_resv_write  

.area _$UART_Init(UART_CODE,REL)
.stabs "UART_Init:F15",36,0,4,_UART_Init
_UART_Init::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\AP4\sio\com.c","UART_Init",61
	LINK #0
	PUSH R1
.stabn 0xc0,0,0,L30-_UART_Init
L30:
.stabn 0x44,0,62,L31-_UART_Init
L31:
.stabn 0x44,0,63,L32-_UART_Init
L32:
	MOV R1,#2
	MOVX _UARBR,R1
.stabn 0x44,0,64,L33-_UART_Init
L33:
	MOV R1,#0x8001
	MOVX _UARCR,R1
.stabn 0x44,0,65,L34-_UART_Init
L34:
	MOV R1,#16
	IGNDS #1
	OR _PBEN,R1
.stabn 0xe0,0,0,L35-_UART_Init
L35:
.stabn 0x44,0,66,L36-_UART_Init
L36:
L29:
	POP R1
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "SendByte:F15",36,0,4,_SendByte

.area _$SendByte(UART_CODE,REL)
_SendByte::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\AP4\sio\com.c","SendByte",187
.stabs "value:p10",160,0,0,6
	LINK #0
	PUSH R1
.stabn 0xc0,0,0,L41-_SendByte
L41:
.stabn 0x44,0,188,L42-_SendByte
L42:
	MOV R1,[FP+#(6)]
	MOVB [FP+#(6)],Rb3
.stabn 0x44,0,195,L43-_SendByte
L43:
	MOVB Rb3,[FP+#(6)]
	MOVZE R1,Rb3
	MOVX _UARTDR,R1
.stabn 0x44,0,196,L44-_SendByte
L44:

			NOP
			NOP
		
.stabn 0x44,0,200,L45-_SendByte
L45:
L38:
.stabn 0x44,0,200,L46-_SendByte
L46:
L39:
.stabn 0x44,0,200,L47-_SendByte
L47:
	MOVX R1,_UARSR
	AND R1,#1
	CMP R1,#0
	AJMP IF_EQ,L38
.stabn 0xe0,0,0,L48-_SendByte
L48:
.stabn 0x44,0,202,L49-_SendByte
L49:
L37:
	POP R1
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "SendString:F15",36,0,4,_SendString

.area _$SendString(UART_CODE,REL)
_SendString::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\AP4\sio\com.c","SendString",298
.stabs ":t34=*2",128,4,0,0
.stabs "p:p34",160,0,0,6
	LINK #0
	PUSH R0
	PUSH R1
	PUSH R2
	PUSH R3
.stabn 0xc0,0,0,L54-_SendString
L54:
.stabn 0x44,0,299,L55-_SendString
L55:
.stabn 0x44,0,301,L56-_SendString
L56:
	AJMP #0,L52
L51:
.stabn 0xc0,0,1,L57-_SendString
L57:
.stabn 0x44,0,302,L58-_SendString
L58:
.stabn 0x44,0,303,L59-_SendString
L59:
	LOAD4$stack R0,R1,6,FP
	MOVDR R2,R3,R0,R1
	ADD R3,#1
	ADDC R2,#0
	SAVE4$stack 6,FP,R2,R3
	LOAD1$indirect Rb1,R0,R1;   Rb1=[R0,R1]
	MOVSE R0,Rb1
	MOVZE R0,Rb1
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _SendByte
	ADD SP,#2
.stabn 0xe0,0,1,L60-_SendString
L60:
.stabn 0x44,0,304,L61-_SendString
L61:
L52:
.stabn 0x44,0,301,L62-_SendString
L62:
	LOAD4$stack R0,R1,6,FP
	LOAD1$indirect Rb1,R0,R1;   Rb1=[R0,R1]
	MOVSE R0,Rb1
	CMP R0,#0
	AJMP IF_NE,L51
.stabn 0xe0,0,0,L63-_SendString
L63:
.stabn 0x44,0,305,L64-_SendString
L64:
L50:
	POP R3
	POP R2
	POP R1
	POP R0
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "send_hex_byte:F15",36,0,4,_send_hex_byte

.area _$send_hex_byte(UART_CODE,REL)
_send_hex_byte::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\AP4\sio\com.c","send_hex_byte",309
.stabs "v:p10",160,0,0,6
	LINK #0
	PUSH R0
.stabn 0xc0,0,0,L66-_send_hex_byte
L66:
.stabn 0x44,0,310,L67-_send_hex_byte
L67:
	MOV R0,[FP+#(6)]
	MOVB [FP+#(6)],Rb1
.stabn 0x44,0,311,L68-_send_hex_byte
L68:
	MOVB Rb1,[FP+#(6)]
	MOVZE R0,Rb1
	AND R0,#240
	ASR R0,#4
	MOVZE R0,Rb1
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _conv
	ADD SP,#2
	MOVZE R0,Rb1
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _SendByte
	ADD SP,#2
.stabn 0x44,0,312,L69-_send_hex_byte
L69:
	MOVB Rb1,[FP+#(6)]
	MOVZE R0,Rb1
	AND R0,#15
	MOVZE R0,Rb1
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _conv
	ADD SP,#2
	MOVZE R0,Rb1
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _SendByte
	ADD SP,#2
.stabn 0xe0,0,0,L70-_send_hex_byte
L70:
.stabn 0x44,0,313,L71-_send_hex_byte
L71:
L65:
	POP R0
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "send_hex_u8:F15",36,0,4,_send_hex_u8

.area _$send_hex_u8(UART_CODE,REL)
_send_hex_u8::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\AP4\sio\com.c","send_hex_u8",325
.stabs "value:p10",160,0,0,6
	LINK #0
	PUSH R0
.stabn 0xc0,0,0,L73-_send_hex_u8
L73:
.stabn 0x44,0,326,L74-_send_hex_u8
L74:
	MOV R0,[FP+#(6)]
	MOVB [FP+#(6)],Rb1
.stabn 0x44,0,327,L75-_send_hex_u8
L75:
	MOV R0,#48
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _SendByte
	ADD SP,#2
.stabn 0x44,0,327,L76-_send_hex_u8
L76:
	MOV R0,#120
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _SendByte
	ADD SP,#2
.stabn 0x44,0,328,L77-_send_hex_u8
L77:
	MOVB Rb1,[FP+#(6)]
	MOVZE R0,Rb1
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _send_hex_byte
	ADD SP,#2
.stabn 0xe0,0,0,L78-_send_hex_u8
L78:
.stabn 0x44,0,329,L79-_send_hex_u8
L79:
L72:
	POP R0
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "send_hex_u16:F15",36,0,4,_send_hex_u16

.area _$send_hex_u16(UART_CODE,REL)
_send_hex_u16::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\AP4\sio\com.c","send_hex_u16",340
.stabs "value:p13",160,0,0,6
	LINK #0
	PUSH R0
.stabn 0xc0,0,0,L81-_send_hex_u16
L81:
.stabn 0x44,0,341,L82-_send_hex_u16
L82:
.stabn 0x44,0,342,L83-_send_hex_u16
L83:
	MOV R0,#48
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _SendByte
	ADD SP,#2
.stabn 0x44,0,342,L84-_send_hex_u16
L84:
	MOV R0,#120
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _SendByte
	ADD SP,#2
.stabn 0x44,0,343,L85-_send_hex_u16
L85:
	MOV R0,[FP+#(6)]
	SR R0,#8
	MOVZE R0,Rb1
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _send_hex_byte
	ADD SP,#2
.stabn 0x44,0,344,L86-_send_hex_u16
L86:
	MOV R0,[FP+#(6)]
	MOVZE R0,Rb1
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _send_hex_byte
	ADD SP,#2
.stabn 0xe0,0,0,L87-_send_hex_u16
L87:
.stabn 0x44,0,345,L88-_send_hex_u16
L88:
L80:
	POP R0
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "send_hex_u32:F15",36,0,4,_send_hex_u32

.area _$send_hex_u32(UART_CODE,REL)
_send_hex_u32::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\AP4\sio\com.c","send_hex_u32",357
.stabs "value:p11",160,0,0,6
	LINK #0
	PUSH R0
	PUSH R1
.stabn 0xc0,0,0,L90-_send_hex_u32
L90:
.stabn 0x44,0,358,L91-_send_hex_u32
L91:
.stabn 0x44,0,359,L92-_send_hex_u32
L92:
	MOV R0,#48
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _SendByte
	ADD SP,#2
.stabn 0x44,0,359,L93-_send_hex_u32
L93:
	MOV R0,#120
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _SendByte
	ADD SP,#2
.stabn 0x44,0,360,L94-_send_hex_u32
L94:
	LOAD4$stack R0,R1,6,FP
	MOV R1,R0
	MOV R0,#0
	SR R1,#(24-16)
	MOVB Rb1,Rb3
	MOVZE R0,Rb1
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _send_hex_byte
	ADD SP,#2
.stabn 0x44,0,361,L95-_send_hex_u32
L95:
	LOAD4$stack R0,R1,6,FP
	MOV R1,R0
	MOV R0,#0
	MOVB Rb1,Rb3
	MOVZE R0,Rb1
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _send_hex_byte
	ADD SP,#2
.stabn 0x44,0,362,L96-_send_hex_u32
L96:
	LOAD4$stack R0,R1,6,FP
	SR R0,#8
	SROSB R1,#8
	MOVB Rb1,Rb3
	MOVZE R0,Rb1
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _send_hex_byte
	ADD SP,#2
.stabn 0x44,0,363,L97-_send_hex_u32
L97:
	LOAD4$stack R0,R1,6,FP
	MOVB Rb1,Rb3
	MOVZE R0,Rb1
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _send_hex_byte
	ADD SP,#2
.stabn 0xe0,0,0,L98-_send_hex_u32
L98:
.stabn 0x44,0,364,L99-_send_hex_u32
L99:
L89:
	POP R1
	POP R0
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "conv:F10",36,0,4,_conv

.area _$conv(UART_CODE,REL)
_conv::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\AP4\sio\com.c","conv",368
.stabs "v:p10",160,0,0,6
	LINK #0
.stabn 0xc0,0,0,L103-_conv
L103:
.stabn 0x44,0,369,L104-_conv
L104:
	MOV R0,[FP+#(6)]
	MOVB [FP+#(6)],Rb1
.stabn 0x44,0,370,L105-_conv
L105:
	MOVB Rb1,[FP+#(6)]
	MOVZE R0,Rb1
	CMP R0,#10
	AJMP IF_SGE,L101
.stabn 0xc0,0,1,L106-_conv
L106:
.stabn 0x44,0,371,L107-_conv
L107:
.stabn 0x44,0,372,L108-_conv
L108:
	MOVB Rb1,[FP+#(6)]
	MOVZE R0,Rb1
	ADD R0,#48
	MOVZE R0,Rb1
	AJMP #0,L100
.stabn 0xe0,0,1,L109-_conv
L109:
.stabn 0x44,0,373,L110-_conv
L110:
L101:
.stabn 0xc0,0,1,L111-_conv
L111:
.stabn 0x44,0,375,L112-_conv
L112:
.stabn 0x44,0,376,L113-_conv
L113:
	MOVB Rb1,[FP+#(6)]
	MOVZE R0,Rb1
	SUB R0,#10
	ADD R0,#97
	MOVZE R0,Rb1
.stabn 0xe0,0,1,L114-_conv
L114:
.stabn 0x44,0,377,L115-_conv
L115:
.stabn 0xe0,0,0,L116-_conv
L116:
.stabn 0x44,0,378,L117-_conv
L117:
L100:
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "_date_n_time:T35=s4year:14,0,7;month:14,7,4;day:14,11,5;\\",128,0,0,0
.stabs "hour:14,16,5;minute:14,21,6;second:14,27,5;;",128,0,0,0
.stabs "_fcb:T36=s86next:37=*36,0,16;used:1,16,16;spec:38=ar1;0;13;10,32,112;\\",128,0,0,0
.stabs "attribute:10,144,8;mode:10,152,8;date_n_time:35,160,32;sector_in_cluster:14,192,16;\\",128,0,0,0
.stabs "first_cluster:11,208,32;last_cluster:11,240,32;cluster:11,272,32;position:11,304,32;\\",128,0,0,0
.stabs "size:11,336,32;dir_cluster:11,368,32;dir_index:14,400,16;dir_first_cluster:11,416,32;\\",128,0,0,0
.stabs "fmode:14,448,16;possible_cluster:11,464,32;entry_index:14,496,16;lfn_cluster:11,512,32;\\",128,0,0,0
.stabs "old_final_cluster:11,544,32;new_start_cluster:11,576,32;pcluster_nodes:39=*14,608,32;\\",128,0,0,0
.stabs "node_count:14,640,16;skips_clusters:14,656,16;drive:1,672,16;;",128,0,0,0
.stabs "_fsinfo:T40=s134bytes_per_sector:14,0,16;sectors_per_cluster:14,16,16;\\",128,0,0,0
.stabs "num_of_fats:14,32,16;dir_entries:14,48,16;total_sectors:11,64,32;\\",128,0,0,0
.stabs "sectors_per_fat:11,96,32;media_id:10,128,8;dummy:10,136,8;first_fat_sector:11,144,32;\\",128,0,0,0
.stabs "first_dir_sector:11,176,32;first_dat_sector:11,208,32;max_cluster_num:11,240,32;\\",128,0,0,0
.stabs "last_cluster_mark:11,272,32;fs_semaphore:39,304,32;internal_slot:36,336,688;\\",128,0,0,0
.stabs "entry_ext:41=ar1;0;5;2,1024,48;;",128,0,0,0
.stabs "_drive:T42=s30drv_clear:43=*44=f1,0,32;drv_read:45=*46=f1,32,32;\\",128,0,0,0
.stabs "drv_write:47=*48=f1,64,32;drv_size:49=*50=f11,96,32;drv_flush:51=*52=f1,128,32;\\",128,0,0,0
.stabs "buffer:53=*10,160,16;sector_in_buffer:11,176,32;buffer_status:14,208,16;\\",128,0,0,0
.stabs "fsinfo:54=*40,224,16;;",128,0,0,0
.stabs "28:T56=s34Drv:42,0,240;pMountFunc:57=*58=f55=eFS_NO_ERROR:0,FS_DRIVE_ERROR:-1,\\",128,0,0,0
.stabs "FS_FORMAT_ERROR:-2,FS_SYSTEM_ERROR:-3,FS_INVALID_DIRECTORY:-4,FS_INVALID_SPEC:-5,\\",128,0,0,0
.stabs "FS_INVALID_MODE:-6,FS_FILE_NOT_FOUND:-7,FS_DIRECTORY_CONFLICT:-8,FS_DIRECTORY_FULL:-9,\\",128,0,0,0
.stabs "FS_OPENFILE_FULL:-10,FS_VOLUME_FULL:-11,FS_ACCESS_DENIED:-12,FS_SEEK_OUT_OF_RANGE:-13,\\",128,0,0,0
.stabs "FS_RENAMING_ERROR:-14,FS_UNRECOVERABLE_FILE:-15,FS_END_DIRECTORY:-16,FS_TRASH_ERROR:-17,\\",128,0,0,0
.stabs "FS_PARAMETER_ERROR:-18,FS_FILE_INCONSISTENT:-19,FS_WRITE_OUT_RANGE:-20,FS_TABLE_INCONSISTENT:-21,\\",128,0,0,0
.stabs "FS_DRIVE_NOT_READY:-22,FS_INVALID_CLUSTER:-23,;,240,32;;",128,0,0,0
.stabs "_fs_entry_info:T59=s2drive:1,0,16;;",128,0,0,0
.stabs "_fat_cache:T60=s12next:61=*60,0,32;drive:1,32,16;index:1,48,16;\\",128,0,0,0
.stabs "state:1,64,16;data:62=ar1;0;1;10,80,16;;",128,0,0,0
.stabs "_fc_trash_info:T63=s12first_cluster:11,0,32;cluster:11,32,32;index:1,64,16;\\",128,0,0,0
.stabs "secidx:1,80,16;;",128,0,0,0
.stabs "_file_info:T64=s280name:65=ar1;0;12;10,0,104;attribute:10,104,8;\\",128,0,0,0
.stabs "date_n_time:35,112,32;size:11,144,32;index:14,176,16;lfn:66=ar1;0;255;10,192,2048;;",128,0,0,0
.stabs "buffer_status:T67=eEMPTY:0,CLEAN:1,DIRTY:2,;",128,0,0,0
.stabs "26:T68=eSDKLOADCODE_NO_ERR:0,SDKLOADCODE_PARAM_ERR:-1,SDKLOADCODE_DATA_ERR:-5,;",128,0,0,0
.stabs "25:T69=eKBLBS_PARSE_CONTENT_OK:1,KBLBS_PARSE_CONTENT_LAST_FRAME:0,KBLBS_PARSE_CONTENT_BITSTREAM_NOT_ENOUGH:-1,\\",128,0,0,0
.stabs "KBLBS_PARSE_CONTENT_ERR_FORMAT:-2,;",128,0,0,0
.stabs "24:T70=s16Version:14,0,16;Mode:14,16,16;Filter:14,32,16;Length:14,48,16;\\",128,0,0,0
.stabs "Timber:14,64,16;Pitch:14,80,16;Speed:14,96,16;HeadLength:14,112,16;;",128,0,0,0
.stabs "23:T71=eKBLBS_PARSE_HEAD_LAST_HEAD:0,KBLBS_PARSE_HEAD_FURTHERMORE_HEAD:1,\\",128,0,0,0
.stabs "KBLBS_PARSE_HEAD_ERR_VERSION:-1,KBLBS_PARSE_HEAD_ERR_MODE:-2,;",128,0,0,0
.stabs "22:T72=s10IMA_SR:14,0,16;IMA_ADPCM_BufSize:14,16,16;IMA_PCM_BufSize:14,32,16;\\",128,0,0,0
.stabs "IMA_Frame_No:11,48,32;;",128,0,0,0
.stabs "21:T73=eSMP_8K:1,SMP_16K:2,SMP_32K:3,SMP_11P025K:4,SMP_22P05K:5,SMP_44P1K:6,\\",128,0,0,0
.stabs "SMP_12K:7,SMP_24K:8,SMP_48K:9,;",128,0,0,0
.stabs "20:T74=eHead_Phone_Out:0,Speaker_Out:1,;",128,0,0,0
.stabs "19:T75=eNo_Mixed_To_DAC:0,Mixed_To_DAC:1,;",128,0,0,0
.stabs "18:T76=eMIC_In:0,Line_In:1,;",128,0,0,0
.stabs "17:T77=eMIC_Gain_0dB:0,MIC_Gain_20dB:1,;",128,0,0,0
.stabs "16:T78=eAUADC_Gain_0dB:0,AUADC_Gain_1P5dB:1,AUADC_Gain_3dB:2,AUADC_Gain_4P5dB:3,\\",128,0,0,0
.stabs "AUADC_Gain_6dB:4,AUADC_Gain_7P5dB:5,AUADC_Gain_9dB:6,AUADC_Gain_10P5dB:7,\\",128,0,0,0
.stabs "AUADC_Gain_12dB:8,AUADC_Gain_13P5dB:9,AUADC_Gain_15dB:10,AUADC_Gain_16P5dB:11,\\",128,0,0,0
.stabs "AUADC_Gain_18dB:12,AUADC_Gain_19P5dB:13,AUADC_Gain_21dB:14,AUADC_Gain_22P5dB:15,;",128,0,0,0
.stabs "15:T79=eAUADC_SAMPLE_RATE_96K:0,AUADC_SAMPLE_RATE_48K:1,AUADC_SAMPLE_RATE_44P1K:2,\\",128,0,0,0
.stabs "AUADC_SAMPLE_RATE_32K:3,AUADC_SAMPLE_RATE_24K:4,AUADC_SAMPLE_RATE_22P05K:5,\\",128,0,0,0
.stabs "AUADC_SAMPLE_RATE_16K:6,AUADC_SAMPLE_RATE_12K:7,AUADC_SAMPLE_RATE_11P025K:8,\\",128,0,0,0
.stabs "AUADC_SAMPLE_RATE_9P6K:9,AUADC_SAMPLE_RATE_8K:10,;",128,0,0,0
.stabs "14:T80=eAUADC_NO_ERR:0,AUADC_SampleRate_SETUP_ERR:-1,AUADC_DTU_SETUP_ERR:-2,\\",128,0,0,0
.stabs "AUADC_OUT_BUF_SETUP_ERR:-3,AUADC_BUF_SIZE_SETUP_ERR:-4,AUADC_CALL_BACK_SETUP_ERR:-5,\\",128,0,0,0
.stabs "AUADC_PARAMETER_SETUP_ERR:-6,AUADC_NO_INIT_ERR:-7,;",128,0,0,0
.stabs "13:T81=eDAC_SAMPLE_RATE_96K:0,DAC_SAMPLE_RATE_48K:1,DAC_SAMPLE_RATE_44P1K:2,\\",128,0,0,0
.stabs "DAC_SAMPLE_RATE_32K:3,DAC_SAMPLE_RATE_24K:4,DAC_SAMPLE_RATE_22P05K:5,DAC_SAMPLE_RATE_16K:6,\\",128,0,0,0
.stabs "DAC_SAMPLE_RATE_12K:7,DAC_SAMPLE_RATE_11P025K:8,DAC_SAMPLE_RATE_9P6K:9,DAC_SAMPLE_RATE_8K:10,;",128,0,0,0
.stabs "12:T82=eDAC_NO_ERR:0,DAC_SAMPLE_RATE_ERR:-1,DAC_NO_SET_FRAME_SIZE:-2,DAC_DTU_SETUP_ERR:-3,\\",128,0,0,0
.stabs "DAC_FRAME_SIZE_ERR:-4,DAC_NO_INIT:-5,DAC_PLL_SETUP_ERR:-6,DAC_SOCR_BIT15_DISABLE:-7,;",128,0,0,0
.stabs "11:T83=eUSB_UPLOAD:16,USB_DOWNLOAD:32,;",128,0,0,0
.stabs "10:T84=eREMOVABLE:128,FIXED:0,;",128,0,0,0
.stabs "9:T85=eDIRECT_ACCESS:0,CDROM:1280,;",128,0,0,0
.stabs "__STORAGE:T86=s38stor_status:87=*88=f1,0,32;stor_size:89=*90=f11,32,32;\\",128,0,0,0
.stabs "stor_read:91=*92=f1,64,32;stor_write:93=*94=f1,96,32;stor_check_wp:95=*96=f1,128,32;\\",128,0,0,0
.stabs "stor_flush:97=*98=f1,160,32;device_type:14,192,16;device_vendor:34,208,32;\\",128,0,0,0
.stabs "device_identify:34,240,32;device_revision:34,272,32;;",128,0,0,0
.stabs "8:T99=eSPI_30M:0,SPI_20M:1,SPI_15M:2,SPI_12M:3,SPI_10M:4,SPI_7P5M:5,SPI_6M:6,\\",128,0,0,0
.stabs "SPI_4M:7,SPI_3M:8,SPI_2M:9,SPI_1M:10,SPI_750K:11,SPI_600K:12,SPI_400K:13,SPI_200K:14,\\",128,0,0,0
.stabs "SPI_100K:15,;",128,0,0,0
.stabs "7:T100=eSPIF_No_Err:0,Do_Not_Support:-1,Parameter_Error:-2,SPIF_No_Space:-3,\\",128,0,0,0
.stabs "Over_RES_Size:-4,Over_FAT_Size:-5,;",128,0,0,0
.stabs "6:T101=eSDTL_No_Err:0,Data_CRC_Err:-1,RSP_CRC_Err:-2,CMD_RSP_Timeout:-3,PRG_Timeout:-4,\\",128,0,0,0
.stabs "SD_Not_Ready_for_Data:-5,Write_Data_Err:-6,Erase_Addr_Err:-7,Erase_Block_No_Err:-8,\\",128,0,0,0
.stabs "Write_To_Protect_ERR:-9,Unusable_Card:-10,No_Card_Inserted:-11,SD_Over_RES_Size:-12,\\",128,0,0,0
.stabs "SD_Over_FAT_Size:-13,Unknown_Err:-14,;",128,0,0,0
.stabs "5:T102=eFEQ_60M:3,FEQ_48M:4,FEQ_40M:5,FEQ_34P28M:6,FEQ_30M:7,FEQ_26P66M:8,\\",128,0,0,0
.stabs "FEQ_24M:9,FEQ_20M:11,FEQ_16M:14,FEQ_15M:15,FEQ_12M:19,FEQ_10M:23,FEQ_9P6M:24,FEQ_8M:29,\\",128,0,0,0
.stabs "FEQ_7P5M:31,;",128,0,0,0
.stabs "4:T103=eDTU0:0,DTU1:1,DTU2:2,DTU3:3,;",128,0,0,0
.stabs "3:T104=eSET_FLASH_BUSY_TRAP:64,CLEAR_FLASH_BUSY_TRAP:65,NFC_DELAY_CALLBACK_TRAP:66,\\",128,0,0,0
.stabs "SD_DELAY_CALLBACK_TRAP:67,STORAGE_SET_BUSY:68,STORAGE_CLR_BUSY:69,Set_File_System_Busy:71,\\",128,0,0,0
.stabs "Clr_File_System_Busy:72,Is_CWrite_Protect:73,FS_Callback:74,GET_DATE_NTIME:75,\\",128,0,0,0
.stabs "I_Change_Drive:76,STACK_OVERFLOW_TRAP:4,STACK_UNDERFLOW_TRAP:8,EXCEPTION_TRAP:12,\\",128,0,0,0
.stabs "TIMER0_INT_TRAP:16,TIMER1_INT_TRAP:18,TIMER2_INT_TRAP:20,TIMER3_INT_TRAP:22,\\",128,0,0,0
.stabs "TIMER4_INT_TRAP:24,I2C_INT_TRAP:30,ADC_INT_TRAP:32,PORT_B_INT_TRAP:34,PORT_C_INT_TRAP:36,\\",128,0,0,0
.stabs "RTC_INT_TRAP:38,CSI_INT_TRAP:40,SPI2_INT_TRAP:42,SPI1_INT_TRAP:44,P80_INT_TRAP:53,\\",128,0,0,0
.stabs "UART_INT_TRAP:54,UART_TX_INT_TRAP:55,UART_RX_INT_TRAP:56,I2SL_INT_TRAP:58,I2SR_INT_TRAP:59,;",128,0,0,0
.stabs "2:T105=u2w:13,0,16;b:62,0,16;;",128,0,0,0
.stabs "1:T106=u4dw:11,0,32;l:11,0,32;w:107=ar1;0;1;13,0,32;b:108=ar1;0;3;10,0,32;;",128,0,0,0
.stabs "_bitref:t14",128,0,0,0
.stabs ":t109=*110=f15",128,4,0,0
.stabs "tStorageBusyCallBackFunc:t109",128,0,0,0
.stabs "tFSDrvHandle:t56",128,0,0,0
.stabs "FS_ENTRY_INFO:t59",128,0,0,0
.stabs "FAT_CACHE:t60",128,0,0,0
.stabs "FSINFO:t40",128,0,0,0
.stabs "FCFILE:t36",128,0,0,0
.stabs "FILE_INFO:t64",128,0,0,0
.stabs "FS_ERR:t55",128,0,0,0
.stabs "wchar_t:t13",128,0,0,0
.stabs "size_t:t11",128,0,0,0
.stabs "ptrdiff_t:t1",128,0,0,0
.stabs "tSDKLoadCodeStatus:t68",128,0,0,0
.stabs "tKBLBSParseContentStatus:t69",128,0,0,0
.stabs "tKBLBSHeadInfo:t70",128,0,0,0
.stabs "tKBLBSParseHeadStatus:t71",128,0,0,0
.stabs "tIMA_INFO:t72",128,0,0,0
.stabs "tMp3SampleRateID:t73",128,0,0,0
.stabs "tMixer_Out:t74",128,0,0,0
.stabs "tMixer_Option:t75",128,0,0,0
.stabs ":t111=*112=f15",128,4,0,0
.stabs "tAUADC_BufNotify:t111",128,0,0,0
.stabs "tAUADC_In_Path:t76",128,0,0,0
.stabs "tAUADC_MIC_Gain:t77",128,0,0,0
.stabs "tAUADC_Input_Gain:t78",128,0,0,0
.stabs "tAUADC_SmapleRate:t79",128,0,0,0
.stabs "tAUADC_Err:t80",128,0,0,0
.stabs "tDAC_SampleRate:t81",128,0,0,0
.stabs "tDAC_Error:t82",128,0,0,0
.stabs "_STORAGE:t86",128,0,0,0
.stabs ":t113=*114=f15",128,4,0,0
.stabs "tSPIFBusyCallBackFunc:t113",128,0,0,0
.stabs "tSPI_Clock:t99",128,0,0,0
.stabs "SPIF_ERR:t100",128,0,0,0
.stabs "SDTL_ERR:t101",128,0,0,0
.stabs ":t115=*116=f15",128,4,0,0
.stabs "PFWAKEUP:t115",128,0,0,0
.stabs "tFEQ:t102",128,0,0,0
.stabs "tKBDM9_DTUNumber:t103",128,0,0,0
.stabs "tKBDM9_TrapNo:t104",128,0,0,0
.stabs "DWord:t11",128,0,0,0
.stabs "Word:t14",128,0,0,0
.stabs "Int32:t6",128,0,0,0
.stabs "Int16:t1",128,0,0,0
.stabs "Int8:t2",128,0,0,0
.stabs "Uint32:t11",128,0,0,0
.stabs "Uint16:t14",128,0,0,0
.stabs "Byte:t10",128,0,0,0
.stabs "Uchar:t10",128,0,0,0
.stabs "Uint8:t10",128,0,0,0
.stabs "WORD:t14",128,0,0,0
.stabs "ULONG:t11",128,0,0,0
.stabs "USHORT:t14",128,0,0,0
.stabs "Dword:t11",128,0,0,0
.stabs "UCHAR:t10",128,0,0,0
.stabs "FP64:t3",128,0,0,0
.stabs "FP32:t4",128,0,0,0
.stabs "INT32S:t6",128,0,0,0
.stabs "INT32U:t11",128,0,0,0
.stabs "INT16S:t1",128,0,0,0
.stabs "INT16U:t14",128,0,0,0
.stabs "INT8S:t9",128,0,0,0
.stabs "INT8U:t10",128,0,0,0
.stabs "BOOLEAN:t10",128,0,0,0
.stabs "Union16:t105",128,0,0,0
.stabs "Union32:t106",128,0,0,0
.stabs "Status_bool:t10",128,0,0,0
.stabs "Status:t10",128,0,0,0
.stabs "Bool:t10",128,0,0,0
.stabs "S32:t6",128,0,0,0
.stabs "S16:t8",128,0,0,0
.stabs "S8:t9",128,0,0,0
.stabs "U32:t11",128,0,0,0
.stabs "U16:t13",128,0,0,0
.stabs "U8:t10",128,0,0,0
.stabs "Float16:t4",128,0,0,0

.area _$com_c$(ROM,REL)
.stabs "", 100, 0, 0,Letext
Letext:
; EXTERN _UARBR
; EXTERN _UARTDR
; EXTERN _UARSR
; EXTERN _UARCR
; EXTERN _PBEN

; THE END
