; Generated by KBCC
.stabs "KBCC",0x3c,0,0,0
.stabs "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\UsbMassStoragev_TSD",0x64,0,3,Ltext0
.stabs "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\Library\GlobalVariable.c",0x64,0,3,Ltext0

.area _$GlobalVariable_c$(ROM,REL)
Ltext0:
.stabs "int:t1=r1;-32768;32767;",128,0,0,0
.stabs "char:t2=r2;-128;127;",128,0,0,0
.stabs "double:t3=r1;8;0;",128,0,0,0
.stabs "float:t4=r1;4;0;",128,0,0,0
.stabs "long double:t5=r1;8;0;",128,0,0,0
.stabs "long int:t6=r1;-2147483648;2147483647;",128,0,0,0
.stabs "long long int:t7=r1;-2147483648;2147483647;",128,0,0,0
.stabs "short:t8=r1;-32768;32767;",128,0,0,0
.stabs "signed char:t9=r1;-128;127;",128,0,0,0
.stabs "unsigned char:t10=r1;0;255;",128,0,0,0
.stabs "unsigned long:t11=r1;0;4294967295;",128,0,0,0
.stabs "unsigned long long:t12=r1;0;4294967295;",128,0,0,0
.stabs "unsigned short:t13=r1;0;65535;",128,0,0,0
.stabs "unsigned int:t14=r1;0;65535;",128,0,0,0
.stabs "void:t15=15",128,0,0,0
.stabs "short __fixed:t16=r1;2;0;",128,0,0,0
.stabs "__fixed:t17=r1;2;0;",128,0,0,0
.stabs "long __fixed:t18=r1;4;0;",128,0,0,0
.stabs "unsigned short __fixed:t19=r1;2;0;",128,0,0,0
.stabs "unsigned __fixed:t20=r1;2;0;",128,0,0,0
.stabs "unsigned long __fixed:t21=r1;4;0;",128,0,0,0
.stabs "__sat short __fixed:t22=r1;2;0;",128,0,0,0
.stabs "__sat __fixed:t23=r1;2;0;",128,0,0,0
.stabs "__sat long __fixed:t24=r1;4;0;",128,0,0,0
.stabs "__sat unsigned short __fixed:t25=r1;2;0;",128,0,0,0
.stabs "__sat unsigned __fixed:t26=r1;2;0;",128,0,0,0
.stabs "__sat unsigned long __fixed:t27=r1;4;0;",128,0,0,0
.stabs "short __accum:t28=r1;4;0;",128,0,0,0
.stabs "__accum:t29=r1;4;0;",128,0,0,0
.stabs "long __accum:t30=r1;6;0;",128,0,0,0
.stabs "unsigned short __accum:t31=r1;4;0;",128,0,0,0
.stabs "unsigned __accum:t32=r1;4;0;",128,0,0,0
.stabs "unsigned long __accum:t33=r1;6;0;",128,0,0,0
.include "kbccmacro.asm"
.stabs "7:T34=s2bRev0:14,0,1;bRev1:14,1,1;bRev2:14,2,1;bRev3:14,3,1;\\",128,0,0,0
.stabs "bRev4:14,4,1;bRev5:14,5,1;bRev6:14,6,1;bRev7:14,7,1;\\",128,0,0,0
.stabs "bRev8:14,8,1;bRev9:14,9,1;bRev10:14,10,1;bRev11:14,11,1;\\",128,0,0,0
.stabs "bRev12:14,12,1;bRev13:14,13,1;bRev14:14,14,1;bRev15:14,15,1;;",128,0,0,0
.stabs "6:T35=u2bits:34,0,16;value:13,0,16;;",128,0,0,0
.stabs "_ClusterListItem:T36=s18disk_id:13,0,16;start_cluster:11,16,32;\\",128,0,0,0
.stabs "offset_by_clus:11,48,32;cluster:11,80,32;seg_len:11,112,32;;",128,0,0,0
.stabs "5:T37=s8Ap3_num:13,0,16;Book_num:13,16,16;Page_num:13,32,16;\\",128,0,0,0
.stabs "Control_num:13,48,16;;",128,0,0,0
.stabs "4:T38=s4Cur_num:13,0,16;Max_num:13,16,16;;",128,0,0,0
.stabs "3:T39=s6Sd_num:13,0,16;Book_num:13,16,16;Book_id:13,32,16;;",128,0,0,0
.stabs "2:T40=u2w:13,0,16;b:41=ar1;0;1;10,0,16;;",128,0,0,0
.stabs "1:T42=u4dw:11,0,32;l:11,0,32;w:43=ar1;0;1;13,0,32;b:44=ar1;0;3;10,0,32;;",128,0,0,0
.stabs "GREV_BIT_NEW:t35",128,0,0,0
.stabs "ClusterListItem:t36",128,0,0,0
.stabs "Record:t37",128,0,0,0
.stabs "BOOKNEWS:t38",128,0,0,0
.stabs "LASTBOOK:t39",128,0,0,0
.stabs "DWord:t11",128,0,0,0
.stabs "Word:t14",128,0,0,0
.stabs "Int32:t6",128,0,0,0
.stabs "Int16:t1",128,0,0,0
.stabs "Int8:t2",128,0,0,0
.stabs "Uint32:t11",128,0,0,0
.stabs "Uint16:t14",128,0,0,0
.stabs "Byte:t10",128,0,0,0
.stabs "Uchar:t10",128,0,0,0
.stabs "Uint8:t10",128,0,0,0
.stabs "WORD:t14",128,0,0,0
.stabs "ULONG:t11",128,0,0,0
.stabs "USHORT:t14",128,0,0,0
.stabs "Dword:t11",128,0,0,0
.stabs "UCHAR:t10",128,0,0,0
.stabs "FP64:t3",128,0,0,0
.stabs "FP32:t4",128,0,0,0
.stabs "INT32S:t6",128,0,0,0
.stabs "INT32U:t11",128,0,0,0
.stabs "INT16S:t1",128,0,0,0
.stabs "INT16U:t14",128,0,0,0
.stabs "INT8S:t9",128,0,0,0
.stabs "INT8U:t10",128,0,0,0
.stabs "BOOLEAN:t10",128,0,0,0
.stabs "Union16:t40",128,0,0,0
.stabs "Union32:t42",128,0,0,0
.stabs "Status_bool:t10",128,0,0,0
.stabs "Status:t10",128,0,0,0
.stabs "Bool:t10",128,0,0,0
.stabs "S32:t6",128,0,0,0
.stabs "S16:t8",128,0,0,0
.stabs "S8:t9",128,0,0,0
.stabs "U32:t11",128,0,0,0
.stabs "U16:t13",128,0,0,0
.stabs "U8:t10",128,0,0,0
.stabs "Float16:t4",128,0,0,0
.stabs "", 100, 0, 0,Letext
Letext:

.area _XRAM$AD$remote_index_tab(XRAM,ABS,dat)
.org 0x6f70
.even
_remote_index_tab::
	.ds 128
.stabs ":t45=ar1;0;31;11",128,0,0,0
.stabs "remote_index_tab:G45",32,0,4,0

.area _XRAM$AD$g_paster_dir(XRAM,ABS,dat)
.org 0x6da6
.even
_g_paster_dir::
	.ds 60
.stabs ":t46=ar1;0;29;14",128,0,0,0
.stabs "g_paster_dir:G46",32,0,4,0

.area _XRAM$AD$g_string2(XRAM,ABS,dat)
.org 0x6f34
.even
_g_string2::
	.ds 60
.stabs "g_string2:G46",32,0,4,0

.area _XRAM$AD$rev_int_2(XRAM,ABS,dat)
.org 0x6ffe
.even
_rev_int_2::
	.ds 2
.stabs "rev_int_2:G14",32,0,4,0

.area _XRAM$AD$rev_int_1(XRAM,ABS,dat)
.org 0x6ffc
.even
_rev_int_1::
	.ds 2
.stabs "rev_int_1:G14",32,0,4,0

.area _XRAM$AD$t01_calib_data3(XRAM,ABS,dat)
.org 0x6f30
.even
_t01_calib_data3::
	.ds 2
.stabs "t01_calib_data3:G14",32,0,4,0

.area _XRAM$AD$t01_calib_data2(XRAM,ABS,dat)
.org 0x6f14
.even
_t01_calib_data2::
	.ds 4
.stabs "t01_calib_data2:G11",32,0,4,0

.area _XRAM$AD$t01_calib_data1(XRAM,ABS,dat)
.org 0x6f10
.even
_t01_calib_data1::
	.ds 4
.stabs "t01_calib_data1:G11",32,0,4,0

.area _XRAM$AD$adc7_value(XRAM,ABS,dat)
.org 0x6ffa
.even
_adc7_value::
	.ds 2
.stabs "adc7_value:G14",32,0,4,0

.area _XRAM$AD$adc3_value(XRAM,ABS,dat)
.org 0x6ff8
.even
_adc3_value::
	.ds 2
.stabs "adc3_value:G14",32,0,4,0

.area _XRAM$AD$adc2_value(XRAM,ABS,dat)
.org 0x6ff6
.even
_adc2_value::
	.ds 2
.stabs "adc2_value:G14",32,0,4,0

.area _XRAM$AD$adc0_value(XRAM,ABS,dat)
.org 0x6ff4
.even
_adc0_value::
	.ds 2
.stabs "adc0_value:G14",32,0,4,0

.area _XRAM$AD$prev_task(XRAM,ABS,dat)
.org 0x6f32
.even
_prev_task::
	.ds 2
.stabs "prev_task:G14",32,0,4,0

.area _XRAM$AD$all_mp3_num(XRAM,ABS,dat)
.org 0x6f02
.even
_all_mp3_num::
	.ds 2
.stabs "all_mp3_num:G14",32,0,4,0

.area _XRAM$AD$current_area(XRAM,ABS,dat)
.org 0x6f08
.even
_current_area::
	.ds 2
.stabs "current_area:G14",32,0,4,0

.area _XRAM$AD$current_playmp3_number(XRAM,ABS,dat)
.org 0x6f0a
.even
_current_playmp3_number::
	.ds 2
.stabs "current_playmp3_number:G14",32,0,4,0

.area _XRAM$AD$current_wav_num(XRAM,ABS,dat)
.org 0x6ff2
.even
_current_wav_num::
	.ds 2
.stabs "current_wav_num:G14",32,0,4,0

.area _XRAM$AD$wav_action(XRAM,ABS,dat)
.org 0x6ff0
.even
_wav_action::
	.ds 2
.stabs "wav_action:G14",32,0,4,0

.area _XRAM$AD$bak_current_index(XRAM,ABS,dat)
.org 0x6f2a
.even
_bak_current_index::
	.ds 2
.stabs "bak_current_index:G14",32,0,4,0

.area _XRAM$AD$volume_inc_flag(XRAM,ABS,dat)
.org 0x6f28
.even
_volume_inc_flag::
	.ds 2
.stabs "volume_inc_flag:G14",32,0,4,0

.area _XRAM$AD$current_mp3_sd(XRAM,ABS,dat)
.org 0x6f06
.even
_current_mp3_sd::
	.ds 2
.stabs "current_mp3_sd:G14",32,0,4,0

.area _XRAM$AD$sd2_ap3_number(XRAM,ABS,dat)
.org 0x6f0c
.even
_sd2_ap3_number::
	.ds 2
.stabs "sd2_ap3_number:G14",32,0,4,0

.area _XRAM$AD$current_sd(XRAM,ABS,dat)
.org 0x6f0e
.even
_current_sd::
	.ds 2
.stabs "current_sd:G14",32,0,4,0

.area _XRAM$AD$ap4_mp3_flag(XRAM,ABS,dat)
.org 0x6f1e
.even
_ap4_mp3_flag::
	.ds 2
.stabs "ap4_mp3_flag:G14",32,0,4,0

.area _XRAM$AD$ap3_file_number(XRAM,ABS,dat)
.org 0x6f1c
.even
_ap3_file_number::
	.ds 2
.stabs "ap3_file_number:G14",32,0,4,0

.area _XRAM$AD$vol_idx(XRAM,ABS,dat)
.org 0x6f1a
.even
_vol_idx::
	.ds 2
.stabs "vol_idx:G14",32,0,4,0

.area _XRAM$AD$rev1Flag(XRAM,ABS,dat)
.org 0x6f2e
.even
_rev1Flag::
	.ds 2
.stabs "rev1Flag:G65571",32,0,4,0

.area _XRAM$AD$sys_flag(XRAM,ABS,dat)
.org 0x6f04
.even
_sys_flag::
	.ds 2
.stabs "sys_flag:G65571",32,0,4,0

.area _XRAM$AD$systerm_flag(XRAM,ABS,dat)
.org 0x6f2c
.even
_systerm_flag::
	.ds 2
.stabs "systerm_flag:G65571",32,0,4,0

.area _XRAM$AD$gflag(XRAM,ABS,dat)
.org 0x6f18
.even
_gflag::
	.ds 2
.stabs "gflag:G65571",32,0,4,0

.area _XRAM$AD$cluster_buf(XRAM,ABS,dat)
.org 0x6de2
.even
_cluster_buf::
	.ds 288
.stabs ":t47=ar1;0;15;36",128,0,0,0
.stabs "cluster_buf:G47",32,0,4,0

.area _XRAM$AD$Current_Record(XRAM,ABS,dat)
.org 0x6f20
.even
_Current_Record::
	.ds 8
.stabs "Current_Record:G37",32,0,4,0

; THE END
