; Generated by KBCC
.stabs "KBCC",0x3c,0,0,0
.stabs "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\UsbMassStoragev_TSD",0x64,0,3,Ltext0
.stabs "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\Library\system\SYSTEM.C",0x64,0,3,Ltext0

.area _$SYSTEM_C$(ROM,REL)
Ltext0:
.stabs "int:t1=r1;-32768;32767;",128,0,0,0
.stabs "char:t2=r2;-128;127;",128,0,0,0
.stabs "double:t3=r1;8;0;",128,0,0,0
.stabs "float:t4=r1;4;0;",128,0,0,0
.stabs "long double:t5=r1;8;0;",128,0,0,0
.stabs "long int:t6=r1;-2147483648;2147483647;",128,0,0,0
.stabs "long long int:t7=r1;-2147483648;2147483647;",128,0,0,0
.stabs "short:t8=r1;-32768;32767;",128,0,0,0
.stabs "signed char:t9=r1;-128;127;",128,0,0,0
.stabs "unsigned char:t10=r1;0;255;",128,0,0,0
.stabs "unsigned long:t11=r1;0;4294967295;",128,0,0,0
.stabs "unsigned long long:t12=r1;0;4294967295;",128,0,0,0
.stabs "unsigned short:t13=r1;0;65535;",128,0,0,0
.stabs "unsigned int:t14=r1;0;65535;",128,0,0,0
.stabs "void:t15=15",128,0,0,0
.stabs "short __fixed:t16=r1;2;0;",128,0,0,0
.stabs "__fixed:t17=r1;2;0;",128,0,0,0
.stabs "long __fixed:t18=r1;4;0;",128,0,0,0
.stabs "unsigned short __fixed:t19=r1;2;0;",128,0,0,0
.stabs "unsigned __fixed:t20=r1;2;0;",128,0,0,0
.stabs "unsigned long __fixed:t21=r1;4;0;",128,0,0,0
.stabs "__sat short __fixed:t22=r1;2;0;",128,0,0,0
.stabs "__sat __fixed:t23=r1;2;0;",128,0,0,0
.stabs "__sat long __fixed:t24=r1;4;0;",128,0,0,0
.stabs "__sat unsigned short __fixed:t25=r1;2;0;",128,0,0,0
.stabs "__sat unsigned __fixed:t26=r1;2;0;",128,0,0,0
.stabs "__sat unsigned long __fixed:t27=r1;4;0;",128,0,0,0
.stabs "short __accum:t28=r1;4;0;",128,0,0,0
.stabs "__accum:t29=r1;4;0;",128,0,0,0
.stabs "long __accum:t30=r1;6;0;",128,0,0,0
.stabs "unsigned short __accum:t31=r1;4;0;",128,0,0,0
.stabs "unsigned __accum:t32=r1;4;0;",128,0,0,0
.stabs "unsigned long __accum:t33=r1;6;0;",128,0,0,0
.include "kbccmacro.asm"
 .define _sdtl_mount	 _sd1_mount        
 .define _sdtl_resv_size	 _sd1_res_size     
 .define _sdtl_get_size	 _sd1_fat_size     
 .define _sdtl_resv_read	 _sd1_res_read     
 .define _sdtl_resv_write	 _sd1_res_write    
 .define _sdtl_read	 _sd1_read         
 .define _sdtl_write	 _sd1_write        
 .define _sdtl_cache_init	 _sd1_cache2k_init 
 .define _sdtl_cache_read	 _sd1_cache_read   
 .define _sdtl_cache_write _sd1_cache_write  
 .define _sdtl_cache_flush _sd1_cache_flush  
 .define _sdtl_allocate    _sd1_allocate     
 .define _spif_res_size	 _spif_resv_size   
 .define _spif_res_read	 _spif_resv_read   
 .define _spif_res_write	 _spif_resv_write  

.area _SYSTEM_CODE$RD$VolTbl(SYSTEM_CODE,REL)
.even
_VolTbl::
	.dw 7 ; 0x7
	.dw 13 ; 0xd
	.dw 20 ; 0x14
	.dw 28 ; 0x1c
	.dw 31 ; 0x1f
.stabs ":t34=ar1;0;4;1",128,0,0,0
.stabs "VolTbl:G34",32,0,3,0

.area _SYSTEM_CODE$RD$SpeakerTbl(SYSTEM_CODE,REL)
.even
_SpeakerTbl::
	.dw 4 ; 0x4
	.dw 5 ; 0x5
	.dw 6 ; 0x6
	.dw 8 ; 0x8
	.dw 10 ; 0xa
.stabs "SpeakerTbl:G34",32,0,3,0

.area _$system_reset(SYSTEM_CODE,REL)
.stabs "system_reset:F15",36,0,4,_system_reset
_system_reset::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\Library\system\SYSTEM.C","system_reset",76
	LINK #0
	PUSH R0
	PUSH R1
.stabn 0xc0,0,0,L49-_system_reset
L49:
.stabn 0x44,0,77,L50-_system_reset
L50:
.stabn 0x44,0,79,L51-_system_reset
L51:
	MOV R1,#(L45)
	MOV R0,#^(L45)
	PUSH R1
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _SendString
	ADD SP,#4
.stabn 0x44,0,81,L52-_system_reset
L52:
	; intrinsic function: __bitCLR
	BCLR 0x57.6
.stabn 0x44,0,82,L53-_system_reset
L53:
	; intrinsic function: __bitSET
	BSET 0x57.7
.stabn 0x44,0,83,L54-_system_reset
L54:
	; intrinsic function: __bitCLR
	BCLR 0x57.5
.stabn 0x44,0,84,L55-_system_reset
L55:
	MOV R0,#0xbfff
	MOVX _RTCWDT,R0
.stabn 0x44,0,85,L56-_system_reset
L56:
L46:
.stabn 0xc0,0,1,L57-_system_reset
L57:
.stabn 0x44,0,86,L58-_system_reset
L58:
.stabn 0xe0,0,1,L59-_system_reset
L59:
.stabn 0x44,0,87,L60-_system_reset
L60:
L47:
.stabn 0x44,0,85,L61-_system_reset
L61:
	AJMP #0,L46
.stabn 0xe0,0,0,L62-_system_reset
L62:
.stabn 0x44,0,88,L63-_system_reset
L63:
	POP R1
	POP R0
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "Exception:F15",36,0,4,_Exception

.area _$Exception(SYSTEM_CODE,REL)
_Exception::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\Library\system\SYSTEM.C","Exception",90
	LINK #0
	SAVE$ISR
	PUSH R0
.stabn 0xc0,0,0,L65-_Exception
L65:
.stabn 0x44,0,91,L66-_Exception
L66:
.stabn 0x44,0,92,L67-_Exception
L67:
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _system_reset
.stabn 0xe0,0,0,L68-_Exception
L68:
.stabn 0x44,0,93,L69-_Exception
L69:
L64:
	POP R0
	RESTORE$ISR
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETI
.stabs "timer_get_time:F11",36,0,4,_timer_get_time

.area _$timer_get_time(SYSTEM_CODE,REL)
_timer_get_time::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\Library\system\SYSTEM.C","timer_get_time",101
	LINK #2
.stabn 0xc0,0,0,L71-_timer_get_time
L71:
.stabn 0x44,0,102,L72-_timer_get_time
L72:
.stabs "time:11",128,0,0,-4
.stabn 0x44,0,106,L73-_timer_get_time
L73:
	LOAD4$memory R0,R1,_g_timer_tick
	SAVE4$stack -4,FP,R0,R1
.stabn 0x44,0,108,L74-_timer_get_time
L74:
	LOAD4$stack R0,R1,-4,FP
.stabn 0xe0,0,0,L75-_timer_get_time
L75:
.stabn 0x44,0,109,L76-_timer_get_time
L76:
L70:
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "timer_check_timeout:F10",36,0,4,_timer_check_timeout

.area _$timer_check_timeout(SYSTEM_CODE,REL)
_timer_check_timeout::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\Library\system\SYSTEM.C","timer_check_timeout",120
.stabs "timer:p11",160,0,0,6
	LINK #0
	PUSH R1
	PUSH R2
	PUSH R3
.stabn 0xc0,0,0,L80-_timer_check_timeout
L80:
.stabn 0x44,0,121,L81-_timer_check_timeout
L81:
.stabn 0x44,0,122,L82-_timer_check_timeout
L82:
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _timer_get_time
	LOAD4$stack R2,R3,6,FP
	CMP$long R0,R1,R2,R3
	AJMP IF_UL,L78
.stabn 0xc0,0,1,L83-_timer_check_timeout
L83:
.stabn 0x44,0,122,L84-_timer_check_timeout
L84:
.stabn 0x44,0,122,L85-_timer_check_timeout
L85:
	MOV R0,#1
	AJMP #0,L77
.stabn 0xe0,0,1,L86-_timer_check_timeout
L86:
.stabn 0x44,0,122,L87-_timer_check_timeout
L87:
L78:
.stabn 0xc0,0,1,L88-_timer_check_timeout
L88:
.stabn 0x44,0,123,L89-_timer_check_timeout
L89:
.stabn 0x44,0,123,L90-_timer_check_timeout
L90:
	MOV R0,#0
.stabn 0xe0,0,1,L91-_timer_check_timeout
L91:
.stabn 0x44,0,123,L92-_timer_check_timeout
L92:
.stabn 0xe0,0,0,L93-_timer_check_timeout
L93:
.stabn 0x44,0,124,L94-_timer_check_timeout
L94:
L77:
	POP R3
	POP R2
	POP R1
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "TIMER0_ISR:F15",36,0,4,_TIMER0_ISR

.area _$TIMER0_ISR(SYSTEM_CODE,REL)
_TIMER0_ISR::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\Library\system\SYSTEM.C","TIMER0_ISR",163
	LINK #0
	SAVE$ISR
	PUSH R0
	PUSH R1
.stabn 0xc0,0,0,L96-_TIMER0_ISR
L96:
.stabn 0x44,0,164,L97-_TIMER0_ISR
L97:
.stabn 0x44,0,165,L98-_TIMER0_ISR
L98:
	MOV R1,#1
	MOV R0,#0
	MOV DS0,#@(_g_timer_tick)
	ADD DS0:(_g_timer_tick+2),R1
	ADDC DS0:(_g_timer_tick),R0
.stabn 0xe0,0,0,L99-_TIMER0_ISR
L99:
.stabn 0x44,0,166,L100-_TIMER0_ISR
L100:
L95:
	POP R1
	POP R0
	RESTORE$ISR
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETI
.stabs "adc_get:F15",36,0,4,_adc_get

.area _$adc_get(SYSTEM_CODE,REL)
_adc_get::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\Library\system\SYSTEM.C","adc_get",195
	LINK #1
	PUSH R0
	PUSH R1
.stabn 0xc0,0,0,L112-_adc_get
L112:
.stabn 0x44,0,196,L113-_adc_get
L113:
.stabs "value:1",128,0,0,-2
.stabn 0x44,0,198,L114-_adc_get
L114:
	LOAD4$memory R0,R1,_adc_timer
	PUSH R1
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _timer_check_timeout
	ADD SP,#4
	MOVZE R0,Rb1
	CMP R0,#0
	AJMP IF_NE,L102
.stabn 0xc0,0,1,L115-_adc_get
L115:
.stabn 0x44,0,199,L116-_adc_get
L116:
.stabn 0x44,0,200,L117-_adc_get
L117:
	AJMP #0,L101
.stabn 0xe0,0,1,L118-_adc_get
L118:
.stabn 0x44,0,201,L119-_adc_get
L119:
L102:
.stabn 0x44,0,203,L120-_adc_get
L120:
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _timer_get_time
	ADD R1,#10
	ADDC R0,#0
	ADD R1,#1
	ADDC R0,#0
	SAVE4$memory _adc_timer,R0,R1; _adc_timer=R0,R1
.stabn 0x44,0,204,L121-_adc_get
L121:
	MOV DS0,#@_adc_channel
	MOVZE R0,DS0:_adc_channel
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _Get_ADCValue
	ADD SP,#2
	MOV [FP+#(-2)],R0
.stabn 0x44,0,206,L122-_adc_get
L122:
	MOV DS0,#@_adc_channel
	MOVZE R0,DS0:_adc_channel
	CMP R0,#0
	AJMP IF_NE,L104
.stabn 0xc0,0,1,L123-_adc_get
L123:
.stabn 0x44,0,206,L124-_adc_get
L124:
.stabn 0x44,0,207,L125-_adc_get
L125:
	MOV R0,[FP+#(-2)]
	MOV DS0,#@_adc0_value
.if KERNEL1_E = 1
	NOP
.endif
	MOV DS0:_adc0_value,R0
.stabn 0x44,0,208,L126-_adc_get
L126:
	MOVB Rb1,#2
	MOV DS0,#@_adc_channel
.if KERNEL1_E = 1
	NOP
.endif
	MOVB DS0:_adc_channel,Rb1
.stabn 0x44,0,209,L127-_adc_get
L127:
	AJMP #0,L101
.stabn 0xe0,0,1,L128-_adc_get
L128:
.stabn 0x44,0,210,L129-_adc_get
L129:
L104:
.stabn 0x44,0,212,L130-_adc_get
L130:
	MOV DS0,#@_adc_channel
	MOVZE R0,DS0:_adc_channel
	CMP R0,#2
	AJMP IF_NE,L106
.stabn 0xc0,0,1,L131-_adc_get
L131:
.stabn 0x44,0,212,L132-_adc_get
L132:
.stabn 0x44,0,213,L133-_adc_get
L133:
	MOV R0,[FP+#(-2)]
	MOV DS0,#@_adc2_value
.if KERNEL1_E = 1
	NOP
.endif
	MOV DS0:_adc2_value,R0
.stabn 0x44,0,214,L134-_adc_get
L134:
	MOVB Rb1,#3
	MOV DS0,#@_adc_channel
.if KERNEL1_E = 1
	NOP
.endif
	MOVB DS0:_adc_channel,Rb1
.stabn 0x44,0,215,L135-_adc_get
L135:
	AJMP #0,L101
.stabn 0xe0,0,1,L136-_adc_get
L136:
.stabn 0x44,0,216,L137-_adc_get
L137:
L106:
.stabn 0x44,0,218,L138-_adc_get
L138:
	MOV DS0,#@_adc_channel
	MOVZE R0,DS0:_adc_channel
	CMP R0,#3
	AJMP IF_NE,L108
.stabn 0xc0,0,1,L139-_adc_get
L139:
.stabn 0x44,0,218,L140-_adc_get
L140:
.stabn 0x44,0,219,L141-_adc_get
L141:
	MOV R0,[FP+#(-2)]
	MOV DS0,#@_adc3_value
.if KERNEL1_E = 1
	NOP
.endif
	MOV DS0:_adc3_value,R0
.stabn 0x44,0,220,L142-_adc_get
L142:
	MOVB Rb1,#7
	MOV DS0,#@_adc_channel
.if KERNEL1_E = 1
	NOP
.endif
	MOVB DS0:_adc_channel,Rb1
.stabn 0x44,0,221,L143-_adc_get
L143:
	AJMP #0,L101
.stabn 0xe0,0,1,L144-_adc_get
L144:
.stabn 0x44,0,222,L145-_adc_get
L145:
L108:
.stabn 0x44,0,224,L146-_adc_get
L146:
	MOV DS0,#@_adc_channel
	MOVZE R0,DS0:_adc_channel
	CMP R0,#7
	AJMP IF_NE,L110
.stabn 0xc0,0,1,L147-_adc_get
L147:
.stabn 0x44,0,224,L148-_adc_get
L148:
.stabn 0x44,0,225,L149-_adc_get
L149:
	MOV R0,[FP+#(-2)]
	MOV DS0,#@_adc7_value
.if KERNEL1_E = 1
	NOP
.endif
	MOV DS0:_adc7_value,R0
.stabn 0x44,0,226,L150-_adc_get
L150:
	MOVB Rb1,#0
	MOV DS0,#@_adc_channel
.if KERNEL1_E = 1
	NOP
.endif
	MOVB DS0:_adc_channel,Rb1
.stabn 0x44,0,227,L151-_adc_get
L151:
	AJMP #0,L101
.stabn 0xe0,0,1,L152-_adc_get
L152:
.stabn 0x44,0,228,L153-_adc_get
L153:
L110:
.stabn 0x44,0,229,L154-_adc_get
L154:
	MOVB Rb1,#7
	MOV DS0,#@_adc_channel
.if KERNEL1_E = 1
	NOP
.endif
	MOVB DS0:_adc_channel,Rb1
.stabn 0xe0,0,0,L155-_adc_get
L155:
.stabn 0x44,0,255,L156-_adc_get
L156:
L101:
	POP R1
	POP R0
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "op_time_dowith:F15",36,0,4,_op_time_dowith

.area _$op_time_dowith(SYSTEM_CODE,REL)
_op_time_dowith::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\Library\system\SYSTEM.C","op_time_dowith",258
	LINK #2
	PUSH R0
	PUSH R1
.stabn 0xc0,0,0,L160-_op_time_dowith
L160:
.stabn 0x44,0,259,L161-_op_time_dowith
L161:
.stabn 0x44,0,260,L162-_op_time_dowith
L162:
	MOVX R0,_op_close_timer
	MOVX R1,_op_close_timer+2
	SAVE4$stack -4,FP,R0,R1
	CMP$long$con R0,R1,0
	AJMP IF_EQ,L158
	LOAD4$stack R0,R1,-4,FP
	PUSH R1
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _timer_check_timeout
	ADD SP,#4
	MOVZE R0,Rb1
	CMP R0,#0
	AJMP IF_EQ,L158
.stabn 0xc0,0,1,L163-_op_time_dowith
L163:
.stabn 0x44,0,260,L164-_op_time_dowith
L164:
.stabn 0x44,0,261,L165-_op_time_dowith
L165:
	MOV R1,#0
	MOV R0,#0
	MOVX _op_close_timer,R0
	MOVX _op_close_timer+2,R1
.stabn 0x44,0,262,L166-_op_time_dowith
L166:
	; intrinsic function: __bitCLR
	BCLR 0x4e.2
.stabn 0xe0,0,1,L167-_op_time_dowith
L167:
.stabn 0x44,0,263,L168-_op_time_dowith
L168:
L158:
.stabn 0xe0,0,0,L169-_op_time_dowith
L169:
.stabn 0x44,0,264,L170-_op_time_dowith
L170:
L157:
	POP R1
	POP R0
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "clk_time_dowith:F15",36,0,4,_clk_time_dowith

.area _$clk_time_dowith(SYSTEM_CODE,REL)
_clk_time_dowith::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\Library\system\SYSTEM.C","clk_time_dowith",265
	LINK #2
	PUSH R0
	PUSH R1
.stabn 0xc0,0,0,L174-_clk_time_dowith
L174:
.stabn 0x44,0,266,L175-_clk_time_dowith
L175:
.stabn 0x44,0,267,L176-_clk_time_dowith
L176:
	LOAD4$memory R0,R1,_g_system_clk_timer
	SAVE4$stack -4,FP,R0,R1
	CMP$long$con R0,R1,0
	AJMP IF_EQ,L172
	LOAD4$stack R0,R1,-4,FP
	PUSH R1
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _timer_check_timeout
	ADD SP,#4
	MOVZE R0,Rb1
	CMP R0,#0
	AJMP IF_EQ,L172
.stabn 0xc0,0,1,L177-_clk_time_dowith
L177:
.stabn 0x44,0,267,L178-_clk_time_dowith
L178:
.stabn 0x44,0,268,L179-_clk_time_dowith
L179:
	MOV R1,#0
	MOV R0,#0
	SAVE4$memory _g_system_clk_timer,R0,R1; _g_system_clk_timer=R0,R1
.stabn 0x44,0,269,L180-_clk_time_dowith
L180:
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _SysClkDowngrade
.stabn 0xe0,0,1,L181-_clk_time_dowith
L181:
.stabn 0x44,0,270,L182-_clk_time_dowith
L182:
L172:
.stabn 0xe0,0,0,L183-_clk_time_dowith
L183:
.stabn 0x44,0,271,L184-_clk_time_dowith
L184:
L171:
	POP R1
	POP R0
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "vol_dec:F15",36,0,4,_vol_dec

.area _$vol_dec(SYSTEM_CODE,REL)
_vol_dec::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\Library\system\SYSTEM.C","vol_dec",272
	LINK #0
.stabn 0xc0,0,0,L186-_vol_dec
L186:
.stabn 0x44,0,273,L187-_vol_dec
L187:
.stabn 0x44,0,275,L188-_vol_dec
L188:
.stabn 0xe0,0,0,L189-_vol_dec
L189:
.stabn 0x44,0,287,L190-_vol_dec
L190:
L185:
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "vol_inc:F15",36,0,4,_vol_inc

.area _$vol_inc(SYSTEM_CODE,REL)
_vol_inc::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\Library\system\SYSTEM.C","vol_inc",288
	LINK #0
.stabn 0xc0,0,0,L192-_vol_inc
L192:
.stabn 0x44,0,289,L193-_vol_inc
L193:
.stabn 0x44,0,291,L194-_vol_inc
L194:
.stabn 0xe0,0,0,L195-_vol_inc
L195:
.stabn 0x44,0,303,L196-_vol_inc
L196:
L191:
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "judge_op:F15",36,0,4,_judge_op

.area _$judge_op(SYSTEM_CODE,REL)
_judge_op::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\Library\system\SYSTEM.C","judge_op",321
	LINK #0
	PUSH R0
	PUSH R1
.stabn 0xc0,0,0,L200-_judge_op
L200:
.stabn 0x44,0,322,L201-_judge_op
L201:
.stabn 0x44,0,323,L202-_judge_op
L202:
	; intrinsic function: __bit_get
	BMOV R0.0,0x59.4
	AND R0,#1
	MOV DS0,#@(_gflag)
	MOV R1,DS0:(_gflag)
	SR R1,#6
	AND R1,#1
	CMP R0,R1
	AJMP IF_EQ,L198
.stabn 0xc0,0,1,L203-_judge_op
L203:
.stabn 0x44,0,323,L204-_judge_op
L204:
.stabn 0x44,0,324,L205-_judge_op
L205:
	MOV R1,#5
	MOV DS0,#@_vol_idx_bak
.if KERNEL1_E = 1
	NOP
.endif
	MOV DS0:_vol_idx_bak,R1
.stabn 0xe0,0,1,L206-_judge_op
L206:
.stabn 0x44,0,325,L207-_judge_op
L207:
L198:
.stabn 0xe0,0,0,L208-_judge_op
L208:
.stabn 0x44,0,326,L209-_judge_op
L209:
L197:
	POP R1
	POP R0
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "inc_volume:F15",36,0,4,_inc_volume

.area _$inc_volume(SYSTEM_CODE,REL)
_inc_volume::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\Library\system\SYSTEM.C","inc_volume",327
.stabs "flag:p10",160,0,0,6
	LINK #0
	PUSH R0
	PUSH R1
.stabn 0xc0,0,0,L215-_inc_volume
L215:
.stabn 0x44,0,328,L216-_inc_volume
L216:
	MOV R1,[FP+#(6)]
	MOVB [FP+#(6)],Rb3
.stabn 0x44,0,330,L217-_inc_volume
L217:
	; intrinsic function: __bit_get
	BMOV R1.0,0x59.4
	AND R1,#1
	MOV DS0,#@(_gflag)
	MOV R0,DS0:(_gflag)
	AND R0,#0xffbf
	AND R1,#1
	SL R1,#6
	AND R1,#64
	OR R0,R1
	MOV DS0,#@_gflag
.if KERNEL1_E = 1
	NOP
.endif
	MOV DS0:_gflag,R0
.stabn 0x44,0,332,L218-_inc_volume
L218:
	MOV DS0,#@(_gflag)
	MOV R0,DS0:(_gflag)
	AND R0,#64
	CMP R0,#0
	AJMP IF_NE,L211
.stabn 0xc0,0,1,L219-_inc_volume
L219:
.stabn 0x44,0,333,L220-_inc_volume
L220:
.stabn 0x44,0,334,L221-_inc_volume
L221:
	; intrinsic function: __bitCLR
	BCLR 0x4e.2
.stabn 0x44,0,336,L222-_inc_volume
L222:
	MOV R0,#5
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _DAC_Speaker_Volume
	ADD SP,#2
.stabn 0xe0,0,1,L223-_inc_volume
L223:
.stabn 0x44,0,337,L224-_inc_volume
L224:
	AJMP #0,L212
L211:
.stabn 0xc0,0,1,L225-_inc_volume
L225:
.stabn 0x44,0,339,L226-_inc_volume
L226:
.stabn 0x44,0,341,L227-_inc_volume
L227:
	; intrinsic function: __bitSET
	BSET 0x4e.2
.stabn 0x44,0,343,L228-_inc_volume
L228:
	MOV DS0,#@_flag_wav_play
	MOVZE R0,DS0:_flag_wav_play
	CMP R0,#0
	AJMP IF_EQ,L213
.stabn 0xc0,0,2,L229-_inc_volume
L229:
.stabn 0x44,0,343,L230-_inc_volume
L230:
.stabn 0x44,0,344,L231-_inc_volume
L231:
	MOV R0,#12
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _DAC_Speaker_Volume
	ADD SP,#2
.stabn 0xe0,0,2,L232-_inc_volume
L232:
.stabn 0x44,0,345,L233-_inc_volume
L233:
	AJMP #0,L214
L213:
.stabn 0xc0,0,2,L234-_inc_volume
L234:
.stabn 0x44,0,346,L235-_inc_volume
L235:
.stabn 0x44,0,351,L236-_inc_volume
L236:
	MOV R0,#8
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _DAC_Speaker_Volume
	ADD SP,#2
.stabn 0xe0,0,2,L237-_inc_volume
L237:
.stabn 0x44,0,353,L238-_inc_volume
L238:
L214:
.stabn 0xe0,0,1,L239-_inc_volume
L239:
.stabn 0x44,0,354,L240-_inc_volume
L240:
L212:
.stabn 0xe0,0,0,L241-_inc_volume
L241:
.stabn 0x44,0,355,L242-_inc_volume
L242:
L210:
	POP R1
	POP R0
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "SpeakDetect:F15",36,0,4,_SpeakDetect

.area _$SpeakDetect(SYSTEM_CODE,REL)
_SpeakDetect::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\Library\system\SYSTEM.C","SpeakDetect",357
.stabs "flag:p10",160,0,0,6
	LINK #0
	PUSH R0
	PUSH R1
	PUSH R2
	PUSH R3
.stabn 0xc0,0,0,L248-_SpeakDetect
L248:
.stabn 0x44,0,358,L249-_SpeakDetect
L249:
	MOV R0,[FP+#(6)]
	MOVB [FP+#(6)],Rb1
.stabn 0x44,0,360,L250-_SpeakDetect
L250:
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _judge_op
.stabn 0x44,0,361,L251-_SpeakDetect
L251:
	MOV DS0,#@(_vol_idx)
	MOV R0,DS0:(_vol_idx)
	MOV DS0,#@(_vol_idx_bak)
	CMP R0,DS0:(_vol_idx_bak)
	AJMP IF_EQ,L244
.stabn 0xc0,0,1,L252-_SpeakDetect
L252:
.stabn 0x44,0,361,L253-_SpeakDetect
L253:
.stabn 0x44,0,362,L254-_SpeakDetect
L254:
	MOV DS0,#@(_vol_idx)
	MOV R0,DS0:(_vol_idx)
	MOV DS0,#@_vol_idx_bak
.if KERNEL1_E = 1
	NOP
.endif
	MOV DS0:_vol_idx_bak,R0
.stabn 0x44,0,364,L255-_SpeakDetect
L255:
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _DAC_Disable_Speaker
.stabn 0x44,0,365,L256-_SpeakDetect
L256:
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _DAC_Enable_HeadPhone
.stabn 0x44,0,367,L257-_SpeakDetect
L257:
	MOV DS0,#@(_sys_flag)
	MOV R0,DS0:(_sys_flag)
	AND R0,#16384
	CMP R0,#0
	AJMP IF_EQ,L246
.stabn 0xc0,0,2,L258-_SpeakDetect
L258:
.stabn 0x44,0,367,L259-_SpeakDetect
L259:
.stabn 0x44,0,368,L260-_SpeakDetect
L260:
	MOV DS0,#@(_VolTbl)
	MOV R0,DS0:(_VolTbl)
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _DAC_HeadPhone_Volume
	ADD SP,#2
.stabn 0xe0,0,2,L261-_SpeakDetect
L261:
.stabn 0x44,0,369,L262-_SpeakDetect
L262:
	AJMP #0,L247
L246:
.stabn 0xc0,0,2,L263-_SpeakDetect
L263:
.stabn 0x44,0,370,L264-_SpeakDetect
L264:
.stabn 0x44,0,371,L265-_SpeakDetect
L265:
	MOV DS0,#@_vol_idx
	MOV R1,DS0:_vol_idx
	MOV R0,#0
	SL R1,#1
	SLOSB R0,#1
	MOV R3,#(_VolTbl)
	MOV R2,#^(_VolTbl)
	ADD R1,R3
	ADDC R0,R2
	LOAD2$indirect R0,R0,R1;   R0=[R0,R1]
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _DAC_HeadPhone_Volume
	ADD SP,#2
.stabn 0xe0,0,2,L266-_SpeakDetect
L266:
.stabn 0x44,0,372,L267-_SpeakDetect
L267:
L247:
.stabn 0x44,0,373,L268-_SpeakDetect
L268:
	MOVB Rb1,[FP+#(6)]
	MOVZE R0,Rb1
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _inc_volume
	ADD SP,#2
.stabn 0xe0,0,1,L269-_SpeakDetect
L269:
.stabn 0x44,0,374,L270-_SpeakDetect
L270:
L244:
.stabn 0xe0,0,0,L271-_SpeakDetect
L271:
.stabn 0x44,0,383,L272-_SpeakDetect
L272:
L243:
	POP R3
	POP R2
	POP R1
	POP R0
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "CheckUSB:F10",36,0,4,_CheckUSB

.area _$CheckUSB(SYSTEM_CODE,REL)
_CheckUSB::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\Library\system\SYSTEM.C","CheckUSB",386
	LINK #0
	PUSH R1
.stabn 0xc0,0,0,L279-_CheckUSB
L279:
.stabn 0x44,0,387,L280-_CheckUSB
L280:
.stabn 0x44,0,388,L281-_CheckUSB
L281:
	MOV DS0,#@(_gflag)
	MOV R0,DS0:(_gflag)
	AND R0,#0x8000
	CMP R0,#0
	AJMP IF_EQ,L274
.stabn 0x44,0,388,L282-_CheckUSB
L282:
	MOV R0,#0
	AJMP #0,L273
L274:
.stabn 0x44,0,389,L283-_CheckUSB
L283:
	MOV DS0,#@(_adc2_value)
	MOV R0,DS0:(_adc2_value)
	CMP R0,#100
	AJMP IF_ULE,L276
.stabn 0xc0,0,1,L284-_CheckUSB
L284:
.stabn 0x44,0,389,L285-_CheckUSB
L285:
.stabn 0x44,0,390,L286-_CheckUSB
L286:
	MOV R0,#0
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _clkup_time
	ADD SP,#2
.stabn 0x44,0,392,L287-_CheckUSB
L287:
	MOV R1,#(L278)
	MOV R0,#^(L278)
	PUSH R1
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _SendString
	ADD SP,#4
.stabn 0x44,0,394,L288-_CheckUSB
L288:
	MOV R1,#0
	MOV R0,#0
	MOVX _sys_led_timer,R0
	MOVX _sys_led_timer+2,R1
.stabn 0x44,0,395,L289-_CheckUSB
L289:
	MOV R0,#1
	AJMP #0,L273
.stabn 0xe0,0,1,L290-_CheckUSB
L290:
.stabn 0x44,0,396,L291-_CheckUSB
L291:
L276:
.stabn 0x44,0,397,L292-_CheckUSB
L292:
	MOV R0,#0
.stabn 0xe0,0,0,L293-_CheckUSB
L293:
.stabn 0x44,0,398,L294-_CheckUSB
L294:
L273:
	POP R1
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "power_forbid_autopoweroff:F15",36,0,4,_power_forbid_autopoweroff

.area _$power_forbid_autopoweroff(SYSTEM_CODE,REL)
_power_forbid_autopoweroff::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\Library\system\SYSTEM.C","power_forbid_autopoweroff",400
	LINK #0
	PUSH R0
.stabn 0xc0,0,0,L296-_power_forbid_autopoweroff
L296:
.stabn 0x44,0,401,L297-_power_forbid_autopoweroff
L297:
.stabn 0x44,0,402,L298-_power_forbid_autopoweroff
L298:
	MOVB Rb1,#1
	MOVBX _g_b_autopoweroff_forbidden,Rb1
.stabn 0xe0,0,0,L299-_power_forbid_autopoweroff
L299:
.stabn 0x44,0,403,L300-_power_forbid_autopoweroff
L300:
L295:
	POP R0
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "power_authorize_autopoweroff:F15",36,0,4,_power_authorize_autopoweroff

.area _$power_authorize_autopoweroff(SYSTEM_CODE,REL)
_power_authorize_autopoweroff::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\Library\system\SYSTEM.C","power_authorize_autopoweroff",414
	LINK #0
	PUSH R0
	PUSH R1
.stabn 0xc0,0,0,L302-_power_authorize_autopoweroff
L302:
.stabn 0x44,0,415,L303-_power_authorize_autopoweroff
L303:
.stabn 0x44,0,417,L304-_power_authorize_autopoweroff
L304:
	MOVB Rb1,#0
	MOVBX _g_b_autopoweroff_forbidden,Rb1
.stabn 0x44,0,419,L305-_power_authorize_autopoweroff
L305:
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _timer_get_time
	ADD R1,#(0x000493e0 & 0xFFFF)
	ADDC R0,#(0x000493e0 >> 16)
	ADD R1,#1
	ADDC R0,#0
	MOVX _g_autopoweroff_timer,R0
	MOVX _g_autopoweroff_timer+2,R1
.stabn 0x44,0,420,L306-_power_authorize_autopoweroff
L306:
	MOV R0,#0xfdff
	MOV DS0,#@(_systerm_flag)
	AND DS0:(_systerm_flag),R0
.stabn 0x44,0,421,L307-_power_authorize_autopoweroff
L307:
	MOV R0,#0xffef
	MOV DS0,#@(_systerm_flag)
	AND DS0:(_systerm_flag),R0
.stabn 0xe0,0,0,L308-_power_authorize_autopoweroff
L308:
.stabn 0x44,0,423,L309-_power_authorize_autopoweroff
L309:
L301:
	POP R1
	POP R0
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS

_Delay_ms::
    LINK #0
    PUSH R0
    PUSH R1

    MOV R0,[FP+#(6)]
$Loop2:
    MOV R1,#12000 ; 
$Loop:
    CMPD1 R1,#0
    AJMP IF_NE,$Loop
    CMPD1 R0,#0
    AJMP IF_NE,$Loop2
    POP R1
    POP R0
    UNLINK_MACRO
    RETS


.area _$SysClkUpgrade(SYSTEM_CODE,REL)
.stabs "SysClkUpgrade:F15",36,0,4,_SysClkUpgrade
_SysClkUpgrade::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\Library\system\SYSTEM.C","SysClkUpgrade",447
	LINK #0
	PUSH R0
	PUSH R1
.stabn 0xc0,0,0,L314-_SysClkUpgrade
L314:
.stabn 0x44,0,448,L315-_SysClkUpgrade
L315:
.stabn 0x44,0,449,L316-_SysClkUpgrade
L316:
	MOV DS0,#@(_gflag)
	MOV R0,DS0:(_gflag)
	AND R0,#1024
	CMP R0,#0
	AJMP IF_EQ,L311
.stabn 0xc0,0,1,L317-_SysClkUpgrade
L317:
.stabn 0x44,0,450,L318-_SysClkUpgrade
L318:
.stabn 0x44,0,451,L319-_SysClkUpgrade
L319:
	MOV R0,#9
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _SystemClock
	ADD SP,#2
.stabn 0x44,0,452,L320-_SysClkUpgrade
L320:
	MOV R0,#3
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _SystemClock
	ADD SP,#2
.stabn 0x44,0,453,L321-_SysClkUpgrade
L321:
	MOV R0,#0
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _SPIF_Set_Clock
	ADD SP,#2
.stabn 0x44,0,454,L322-_SysClkUpgrade
L322:
	MOV R0,#0xfbff
	MOV DS0,#@(_gflag)
	AND DS0:(_gflag),R0
.stabn 0x44,0,456,L323-_SysClkUpgrade
L323:
	MOV R1,#(L313)
	MOV R0,#^(L313)
	PUSH R1
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _SendString
	ADD SP,#4
.stabn 0xe0,0,1,L324-_SysClkUpgrade
L324:
.stabn 0x44,0,458,L325-_SysClkUpgrade
L325:
L311:
.stabn 0xe0,0,0,L326-_SysClkUpgrade
L326:
.stabn 0x44,0,460,L327-_SysClkUpgrade
L327:
L310:
	POP R1
	POP R0
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "SysClkDowngrade:F15",36,0,4,_SysClkDowngrade

.area _$SysClkDowngrade(SYSTEM_CODE,REL)
_SysClkDowngrade::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\Library\system\SYSTEM.C","SysClkDowngrade",464
	LINK #0
	PUSH R0
	PUSH R1
.stabn 0xc0,0,0,L332-_SysClkDowngrade
L332:
.stabn 0x44,0,465,L333-_SysClkDowngrade
L333:
.stabn 0x44,0,466,L334-_SysClkDowngrade
L334:
	MOV DS0,#@(_gflag)
	MOV R0,DS0:(_gflag)
	AND R0,#1024
	CMP R0,#0
	AJMP IF_NE,L329
.stabn 0xc0,0,1,L335-_SysClkDowngrade
L335:
.stabn 0x44,0,467,L336-_SysClkDowngrade
L336:
.stabn 0x44,0,469,L337-_SysClkDowngrade
L337:
	MOV R1,#(L331)
	MOV R0,#^(L331)
	PUSH R1
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _SendString
	ADD SP,#4
.stabn 0x44,0,471,L338-_SysClkDowngrade
L338:
	MOV R0,#8
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _SPIF_Set_Clock
	ADD SP,#2
.stabn 0x44,0,472,L339-_SysClkDowngrade
L339:

         BCLR MODCON.12
         REP #45
   		NOP
      
.stabn 0x44,0,479,L340-_SysClkDowngrade
L340:
	MOV R0,#1024
	MOV DS0,#@(_gflag)
	OR DS0:(_gflag),R0
.stabn 0xe0,0,1,L341-_SysClkDowngrade
L341:
.stabn 0x44,0,480,L342-_SysClkDowngrade
L342:
L329:
.stabn 0xe0,0,0,L343-_SysClkDowngrade
L343:
.stabn 0x44,0,482,L344-_SysClkDowngrade
L344:
L328:
	POP R1
	POP R0
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "clkup_time:F15",36,0,4,_clkup_time

.area _$clkup_time(SYSTEM_CODE,REL)
_clkup_time::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\Library\system\SYSTEM.C","clkup_time",484
.stabs "flag_on:p10",160,0,0,6
	LINK #0
	PUSH R0
	PUSH R1
.stabn 0xc0,0,0,L348-_clkup_time
L348:
.stabn 0x44,0,485,L349-_clkup_time
L349:
	MOV R0,[FP+#(6)]
	MOVB [FP+#(6)],Rb1
.stabn 0x44,0,486,L350-_clkup_time
L350:
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _SysClkUpgrade
.stabn 0x44,0,487,L351-_clkup_time
L351:
	MOVB Rb1,[FP+#(6)]
	MOVZE R0,Rb1
	CMP R0,#0
	AJMP IF_EQ,L346
.stabn 0xc0,0,1,L352-_clkup_time
L352:
.stabn 0x44,0,487,L353-_clkup_time
L353:
.stabn 0x44,0,488,L354-_clkup_time
L354:
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _timer_get_time
	ADD R1,#2000
	ADDC R0,#0
	ADD R1,#1
	ADDC R0,#0
	SAVE4$memory _g_system_clk_timer,R0,R1; _g_system_clk_timer=R0,R1
.stabn 0xe0,0,1,L355-_clkup_time
L355:
.stabn 0x44,0,490,L356-_clkup_time
L356:
	AJMP #0,L347
L346:
.stabn 0xc0,0,1,L357-_clkup_time
L357:
.stabn 0x44,0,491,L358-_clkup_time
L358:
.stabn 0x44,0,492,L359-_clkup_time
L359:
	MOV R1,#0
	MOV R0,#0
	SAVE4$memory _g_system_clk_timer,R0,R1; _g_system_clk_timer=R0,R1
.stabn 0xe0,0,1,L360-_clkup_time
L360:
.stabn 0x44,0,493,L361-_clkup_time
L361:
L347:
.stabn 0xe0,0,0,L362-_clkup_time
L362:
.stabn 0x44,0,494,L363-_clkup_time
L363:
L345:
	POP R1
	POP R0
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "time3_init:F15",36,0,4,_time3_init

.area _$time3_init(SYSTEM_TIMER3_INIT_CODE,REL)
_time3_init::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\Library\system\SYSTEM.C","time3_init",517
	LINK #0
	PUSH R0
	PUSH R1
.stabn 0xc0,0,0,L365-_time3_init
L365:
.stabn 0x44,0,518,L366-_time3_init
L366:
.stabn 0x44,0,520,L367-_time3_init
L367:
	MOV R1,#(_TIMER0_ISR)
	MOV R0,#^(_TIMER0_ISR)
	PUSH R1
	PUSH R0
	MOV R0,#22
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _SetVector
	ADD SP,#6
.stabn 0x44,0,521,L368-_time3_init
L368:
	MOV R0,#0xd005
	MOVX _TMR3CR,R0
.stabn 0x44,0,523,L369-_time3_init
L369:
	MOV R0,#750
	MOVX _TM3PRD,R0
.stabn 0x44,0,524,L370-_time3_init
L370:
	MOV R0,#1
	MOVX _TM3ICR,R0
.stabn 0x44,0,525,L371-_time3_init
L371:
	MOV R1,#0
	MOV R0,#0
	SAVE4$memory _g_timer_tick,R0,R1; _g_timer_tick=R0,R1
.stabn 0xe0,0,0,L372-_time3_init
L372:
.stabn 0x44,0,537,L373-_time3_init
L373:
L364:
	POP R1
	POP R0
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "System_Timer3_Init:F15",36,0,4,_System_Timer3_Init

.area _$System_Timer3_Init(SYSTEM_TIMER3_INIT_CODE,REL)
_System_Timer3_Init::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\Library\system\SYSTEM.C","System_Timer3_Init",541
	LINK #0
	PUSH R0
	PUSH R1
.stabn 0xc0,0,0,L375-_System_Timer3_Init
L375:
.stabn 0x44,0,542,L376-_System_Timer3_Init
L376:
.stabn 0x44,0,543,L377-_System_Timer3_Init
L377:
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _time3_init
.stabn 0x44,0,547,L378-_System_Timer3_Init
L378:
	; intrinsic function: __bit_get
	BMOV R0.0,0x59.4
	AND R0,#1
	MOV DS0,#@(_gflag)
	MOV R1,DS0:(_gflag)
	AND R1,#0xffbf
	AND R0,#1
	SL R0,#6
	AND R0,#64
	OR R1,R0
	MOV DS0,#@_gflag
.if KERNEL1_E = 1
	NOP
.endif
	MOV DS0:_gflag,R1
.stabn 0x44,0,548,L379-_System_Timer3_Init
L379:
	MOVB Rb3,#0
	MOV DS0,#@_battery_count
.if KERNEL1_E = 1
	NOP
.endif
	MOVB DS0:_battery_count,Rb3
.stabn 0x44,0,549,L380-_System_Timer3_Init
L380:
	MOVB Rb3,#0
	MOV DS0,#@_adc_channel
.if KERNEL1_E = 1
	NOP
.endif
	MOVB DS0:_adc_channel,Rb3
.stabn 0x44,0,550,L381-_System_Timer3_Init
L381:
	MOV R1,#1
	MOV R0,#0
	SAVE4$memory _adc_timer,R0,R1; _adc_timer=R0,R1
.stabn 0x44,0,553,L382-_System_Timer3_Init
L382:
	MOV R1,#0
	MOV R0,#0
	MOVX _sys_led_timer,R0
	MOVX _sys_led_timer+2,R1
.stabn 0x44,0,554,L383-_System_Timer3_Init
L383:
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _timer_get_time
	ADD R1,#50
	ADDC R0,#0
	ADD R1,#1
	ADDC R0,#0
	MOVX _sys_led_timer,R0
	MOVX _sys_led_timer+2,R1
.stabn 0x44,0,555,L384-_System_Timer3_Init
L384:
	MOVB Rb1,#0
	MOV DS0,#@_flag_tishi
.if KERNEL1_E = 1
	NOP
.endif
	MOVB DS0:_flag_tishi,Rb1
.stabn 0x44,0,556,L385-_System_Timer3_Init
L385:
	MOV R1,#0
	MOV R0,#0
	MOVX _op_close_timer,R0
	MOVX _op_close_timer+2,R1
.stabn 0x44,0,557,L386-_System_Timer3_Init
L386:
	MOV R1,#0
	MOV R0,#0
	MOVX _rec_led_timer,R0
	MOVX _rec_led_timer+2,R1
.stabn 0x44,0,558,L387-_System_Timer3_Init
L387:
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _timer_get_time
	ADD R1,#25
	ADDC R0,#0
	ADD R1,#1
	ADDC R0,#0
	MOVX _rec_led_timer,R0
	MOVX _rec_led_timer+2,R1
.stabn 0x44,0,559,L388-_System_Timer3_Init
L388:
	MOVB Rb1,#1
	MOV DS0,#@_flag_tishi
.if KERNEL1_E = 1
	NOP
.endif
	MOVB DS0:_flag_tishi,Rb1
.stabn 0x44,0,561,L389-_System_Timer3_Init
L389:
	MOV R0,#0
	MOV DS0,#@_sleep_mode_count
.if KERNEL1_E = 1
	NOP
.endif
	MOV DS0:_sleep_mode_count,R0
.stabn 0x44,0,562,L390-_System_Timer3_Init
L390:
	MOV R1,#0
	MOV R0,#0
	SAVE4$memory _sleep_mode_timer,R0,R1; _sleep_mode_timer=R0,R1
.stabn 0xe0,0,0,L391-_System_Timer3_Init
L391:
.stabn 0x44,0,565,L392-_System_Timer3_Init
L392:
L374:
	POP R1
	POP R0
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "BatteryDetect:F10",36,0,4,_BatteryDetect

.area _$BatteryDetect(BATTERY_CODE,REL)
_BatteryDetect::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\Library\system\SYSTEM.C","BatteryDetect",641
	LINK #2
	PUSH R1
	PUSH R2
	PUSH R3
.stabn 0xc0,0,0,L401-_BatteryDetect
L401:
.stabn 0x44,0,642,L402-_BatteryDetect
L402:
.stabs "temp_Value:14",128,0,0,-2
.stabs "temp_data:13",128,0,0,-4
.stabn 0x44,0,645,L403-_BatteryDetect
L403:
	MOV DS0,#@(_adc2_value)
	MOV R0,DS0:(_adc2_value)
	CMP R0,#100
	AJMP IF_ULE,L394
.stabn 0x44,0,645,L404-_BatteryDetect
L404:
	MOV R0,#0
	AJMP #0,L393
L394:
.stabn 0x44,0,650,L405-_BatteryDetect
L405:
	MOV R1,#100
	MOV R0,#0
	MOV DS0,#@_adc0_value
	MOV R3,DS0:_adc0_value
	MOV R2,#0
	MUL$ulong R0,R1,R2,R3
	MOV DS0,#@_adc7_value
	MOV R3,DS0:_adc7_value
	MOV R2,#0
	DIV$ulong R0,R1,R2,R3
	MOV R0,R1
	MOV [FP+#(-2)],R0
.stabn 0x44,0,651,L406-_BatteryDetect
L406:
	MOV R0,[FP+#(-2)]
	CMP R0,#89
	AJMP IF_UGE,L396
.stabn 0xc0,0,1,L407-_BatteryDetect
L407:
.stabn 0x44,0,652,L408-_BatteryDetect
L408:
.stabn 0x44,0,653,L409-_BatteryDetect
L409:
	MOV DS0,#@_battery_count
	MOVZE R0,DS0:_battery_count
	ADD R0,#1
	MOV DS0,#@_battery_count
.if KERNEL1_E = 1
	NOP
.endif
	MOVB DS0:_battery_count,Rb1
.stabn 0x44,0,654,L410-_BatteryDetect
L410:
	MOV DS0,#@_battery_count
	MOVZE R0,DS0:_battery_count
	CMP R0,#20
	AJMP IF_SL,L397
.stabn 0xc0,0,2,L411-_BatteryDetect
L411:
.stabn 0x44,0,655,L412-_BatteryDetect
L412:
.stabn 0x44,0,657,L413-_BatteryDetect
L413:
	MOV R1,#(L400)
	MOV R0,#^(L400)
	PUSH R1
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _SendString
	ADD SP,#4
.stabn 0x44,0,659,L414-_BatteryDetect
L414:
	MOV R0,#0
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _clkup_time
	ADD SP,#2
.stabn 0x44,0,660,L415-_BatteryDetect
L415:
	; intrinsic function: __bitSET
	BSET 0x57.6
.stabn 0x44,0,661,L416-_BatteryDetect
L416:
	; intrinsic function: __bitCLR
	BCLR 0x57.7
.stabn 0x44,0,662,L417-_BatteryDetect
L417:
	MOV R1,#0
	MOV R0,#0
	MOVX _sys_led_timer,R0
	MOVX _sys_led_timer+2,R1
.stabn 0x44,0,663,L418-_BatteryDetect
L418:
	MOV R0,#4
	MOV DS0,#@(_gflag)
	OR DS0:(_gflag),R0
.stabn 0x44,0,665,L419-_BatteryDetect
L419:
	MOV R0,#1
	AJMP #0,L393
.stabn 0xe0,0,2,L420-_BatteryDetect
L420:
.stabn 0x44,0,666,L421-_BatteryDetect
L421:
.stabn 0xe0,0,1,L422-_BatteryDetect
L422:
.stabn 0x44,0,667,L423-_BatteryDetect
L423:
L396:
.stabn 0xc0,0,1,L424-_BatteryDetect
L424:
.stabn 0x44,0,668,L425-_BatteryDetect
L425:
.stabn 0x44,0,669,L426-_BatteryDetect
L426:
	MOVB Rb1,#0
	MOV DS0,#@_battery_count
.if KERNEL1_E = 1
	NOP
.endif
	MOVB DS0:_battery_count,Rb1
.stabn 0x44,0,670,L427-_BatteryDetect
L427:
	MOV R0,#0xfffb
	MOV DS0,#@(_gflag)
	AND DS0:(_gflag),R0
.stabn 0xe0,0,1,L428-_BatteryDetect
L428:
.stabn 0x44,0,671,L429-_BatteryDetect
L429:
L397:
.stabn 0x44,0,672,L430-_BatteryDetect
L430:
	MOV R0,#0
.stabn 0xe0,0,0,L431-_BatteryDetect
L431:
.stabn 0x44,0,673,L432-_BatteryDetect
L432:
L393:
	POP R3
	POP R2
	POP R1
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "43:T35=s14dwTOC_Offset:11,0,32;wVbriTOC_Size:14,32,16;wVbriDelay:14,48,16;\\",128,0,0,0
.stabs "wVbriTOC_Scale:14,64,16;wVbriTOC_EntryBytes:14,80,16;wVbriTOC_EntryFrames:14,96,16;;",128,0,0,0
.stabs "42:T36=s58dwFileSize:11,0,32;dwHeaderOffset:11,32,32;dwAudioFileSize:11,64,32;\\",128,0,0,0
.stabs "dwFilePosition:11,96,32;dwTimeLength:11,128,32;dwTimePosition:11,160,32;\\",128,0,0,0
.stabs "dwFrameTotal:11,192,32;dwFrameCount:11,224,32;bVersionID:10,256,8;\\",128,0,0,0
.stabs "bLayer:10,264,8;bVBRType:10,272,8;bChannel:10,280,8;wBitRate:14,288,16;\\",128,0,0,0
.stabs "wSampleRate:14,304,16;wFrameSize:14,320,16;wSamplePerFrame:14,336,16;\\",128,0,0,0
.stabs "wFrameDuration:14,352,16;bPaddingSize:10,368,8;bCRCs:10,376,8;bPrivate:10,384,8;\\",128,0,0,0
.stabs "bCopyright:10,392,8;bOriginal:10,400,8;bEmphasis:10,408,8;wID3v1Size:14,416,16;\\",128,0,0,0
.stabs "dwID3v2Size:11,432,32;;",128,0,0,0
.stabs "_date_n_time:T37=s4year:14,0,7;month:14,7,4;day:14,11,5;\\",128,0,0,0
.stabs "hour:14,16,5;minute:14,21,6;second:14,27,5;;",128,0,0,0
.stabs "_fcb:T38=s86next:39=*38,0,16;used:1,16,16;spec:40=ar1;0;13;10,32,112;\\",128,0,0,0
.stabs "attribute:10,144,8;mode:10,152,8;date_n_time:37,160,32;sector_in_cluster:14,192,16;\\",128,0,0,0
.stabs "first_cluster:11,208,32;last_cluster:11,240,32;cluster:11,272,32;position:11,304,32;\\",128,0,0,0
.stabs "size:11,336,32;dir_cluster:11,368,32;dir_index:14,400,16;dir_first_cluster:11,416,32;\\",128,0,0,0
.stabs "fmode:14,448,16;possible_cluster:11,464,32;entry_index:14,496,16;lfn_cluster:11,512,32;\\",128,0,0,0
.stabs "old_final_cluster:11,544,32;new_start_cluster:11,576,32;pcluster_nodes:41=*14,608,32;\\",128,0,0,0
.stabs "node_count:14,640,16;skips_clusters:14,656,16;drive:1,672,16;;",128,0,0,0
.stabs "41:T44=s196FSHandle:45=*38,0,16;Status:42=eINIT_STATUS:0,OPEN_STATUS:1,\\",128,0,0,0
.stabs "CLOSE_STATUS:2,UNINIT_STATUS:3,PLAYING_STATUS:4,PAUSE_STATUS:5,STOP_STATUS:6,\\",128,0,0,0
.stabs "EOF_STATUS:7,AB_REPEAT_STATUS:8,A_STAGE_STATUS:9,FWRWD_PROLOG_STATUS:10,FORWARD_STATUS:11,\\",128,0,0,0
.stabs "REWIND_STATUS:12,FWRWD_EPILOG_STATUS:13,ERROR_STATUS:14,;,16,16;SpectrumData:46=ar1;0;31;14,32,512;\\",128,0,0,0
.stabs "ID3v1_Data:43=s128TAG_id:47=ar1;0;2;10,0,24;Song_title:48=ar1;0;29;10,24,240;\\",128,0,0,0
.stabs "Artist:48,264,240;Album:48,504,240;Year:49=ar1;0;3;10,744,32;Comment:48,776,240;\\",128,0,0,0
.stabs "Genre:50=ar1;0;0;10,1016,8;;,544,1024;;",128,0,0,0
.stabs "39:T51=eMP3API_ERR:-1,MP3API_NO_ERR:0,;",128,0,0,0
.stabs "37:T52=eEQ_USER:-2,EQ_NOMAL:-1,EQ_ROCK:0,EQ_POP:1,EQ_CLASSICAL:2,EQ_SOFT:3,\\",128,0,0,0
.stabs "EQ_JAZZ:4,EQ_BASS:5,;",128,0,0,0
.stabs "36:T53=s12EqMax:14,0,16;EqBand:14,16,16;EqConstTBL:54=*41,32,32;\\",128,0,0,0
.stabs "EqUserTBL:41,64,32;;",128,0,0,0
.stabs "35:T55=eAUDIO_ERROR_OK:0,AUDIO_ERROR_PCM_INIT:-1,AUDIO_ERROR_PCM_UNINIT:-2,\\",128,0,0,0
.stabs "AUDIO_ERROR_OPNE_FILE:-3,AUDIO_ERROR_READ_FILE:-4,AUDIO_ERROR_SEEK_FILE:-5,\\",128,0,0,0
.stabs "AUDIO_ERROR_PCM_GO:-6,AUDIO_ERROR_MP3DECODE:-7,AUDIO_ERROR_PARAMETER:-8,AUDIO_ERROR_CLOSE_FILE:-9,\\",128,0,0,0
.stabs "AUDIO_ERROR_SETVOLUME:-10,AUDIO_ERROR_FW_RWD:-11,AUDIO_ERROR_EOF:-12,AUDIO_ERROR_LOADCODE:-13,;",128,0,0,0
.stabs "34:T56=eHEADER_PHONE:0,SPEAKER:1,;",128,0,0,0
.stabs "33:T57=s2bRev0:14,0,1;bRev1:14,1,1;bRev2:14,2,1;bRev3:14,3,1;\\",128,0,0,0
.stabs "bRev4:14,4,1;bRev5:14,5,1;bRev6:14,6,1;bRev7:14,7,1;\\",128,0,0,0
.stabs "bRev8:14,8,1;bRev9:14,9,1;bRev10:14,10,1;bRev11:14,11,1;\\",128,0,0,0
.stabs "bRev12:14,12,1;bRev13:14,13,1;bRev14:14,14,1;bRev15:14,15,1;;",128,0,0,0
.stabs "32:T58=u2bits:57,0,16;value:13,0,16;;",128,0,0,0
.stabs "_ClusterListItem:T59=s18disk_id:13,0,16;start_cluster:11,16,32;\\",128,0,0,0
.stabs "offset_by_clus:11,48,32;cluster:11,80,32;seg_len:11,112,32;;",128,0,0,0
.stabs "31:T60=s8Ap3_num:13,0,16;Book_num:13,16,16;Page_num:13,32,16;\\",128,0,0,0
.stabs "Control_num:13,48,16;;",128,0,0,0
.stabs "30:T61=s4Cur_num:13,0,16;Max_num:13,16,16;;",128,0,0,0
.stabs "29:T62=s6Sd_num:13,0,16;Book_num:13,16,16;Book_id:13,32,16;;",128,0,0,0
.stabs "28:T63=u2w:13,0,16;b:64=ar1;0;1;10,0,16;;",128,0,0,0
.stabs "27:T65=u4dw:11,0,32;l:11,0,32;w:66=ar1;0;1;13,0,32;b:49,0,32;;",128,0,0,0
.stabs "_fsinfo:T67=s134bytes_per_sector:14,0,16;sectors_per_cluster:14,16,16;\\",128,0,0,0
.stabs "num_of_fats:14,32,16;dir_entries:14,48,16;total_sectors:11,64,32;\\",128,0,0,0
.stabs "sectors_per_fat:11,96,32;media_id:10,128,8;dummy:10,136,8;first_fat_sector:11,144,32;\\",128,0,0,0
.stabs "first_dir_sector:11,176,32;first_dat_sector:11,208,32;max_cluster_num:11,240,32;\\",128,0,0,0
.stabs "last_cluster_mark:11,272,32;fs_semaphore:41,304,32;internal_slot:38,336,688;\\",128,0,0,0
.stabs "entry_ext:68=ar1;0;5;2,1024,48;;",128,0,0,0
.stabs "_drive:T69=s30drv_clear:70=*71=f1,0,32;drv_read:72=*73=f1,32,32;\\",128,0,0,0
.stabs "drv_write:74=*75=f1,64,32;drv_size:76=*77=f11,96,32;drv_flush:78=*79=f1,128,32;\\",128,0,0,0
.stabs "buffer:80=*10,160,16;sector_in_buffer:11,176,32;buffer_status:14,208,16;\\",128,0,0,0
.stabs "fsinfo:81=*67,224,16;;",128,0,0,0
.stabs "26:T83=s34Drv:69,0,240;pMountFunc:84=*85=f82=eFS_NO_ERROR:0,FS_DRIVE_ERROR:-1,\\",128,0,0,0
.stabs "FS_FORMAT_ERROR:-2,FS_SYSTEM_ERROR:-3,FS_INVALID_DIRECTORY:-4,FS_INVALID_SPEC:-5,\\",128,0,0,0
.stabs "FS_INVALID_MODE:-6,FS_FILE_NOT_FOUND:-7,FS_DIRECTORY_CONFLICT:-8,FS_DIRECTORY_FULL:-9,\\",128,0,0,0
.stabs "FS_OPENFILE_FULL:-10,FS_VOLUME_FULL:-11,FS_ACCESS_DENIED:-12,FS_SEEK_OUT_OF_RANGE:-13,\\",128,0,0,0
.stabs "FS_RENAMING_ERROR:-14,FS_UNRECOVERABLE_FILE:-15,FS_END_DIRECTORY:-16,FS_TRASH_ERROR:-17,\\",128,0,0,0
.stabs "FS_PARAMETER_ERROR:-18,FS_FILE_INCONSISTENT:-19,FS_WRITE_OUT_RANGE:-20,FS_TABLE_INCONSISTENT:-21,\\",128,0,0,0
.stabs "FS_DRIVE_NOT_READY:-22,FS_INVALID_CLUSTER:-23,;,240,32;;",128,0,0,0
.stabs "_fs_entry_info:T86=s2drive:1,0,16;;",128,0,0,0
.stabs "_fat_cache:T87=s12next:88=*87,0,32;drive:1,32,16;index:1,48,16;\\",128,0,0,0
.stabs "state:1,64,16;data:64,80,16;;",128,0,0,0
.stabs "_fc_trash_info:T89=s12first_cluster:11,0,32;cluster:11,32,32;index:1,64,16;\\",128,0,0,0
.stabs "secidx:1,80,16;;",128,0,0,0
.stabs "_file_info:T90=s280name:91=ar1;0;12;10,0,104;attribute:10,104,8;\\",128,0,0,0
.stabs "date_n_time:37,112,32;size:11,144,32;index:14,176,16;lfn:92=ar1;0;255;10,192,2048;;",128,0,0,0
.stabs "buffer_status:T93=eEMPTY:0,CLEAN:1,DIRTY:2,;",128,0,0,0
.stabs "24:T94=eSDKLOADCODE_NO_ERR:0,SDKLOADCODE_PARAM_ERR:-1,SDKLOADCODE_DATA_ERR:-5,;",128,0,0,0
.stabs "23:T95=eKBLBS_PARSE_CONTENT_OK:1,KBLBS_PARSE_CONTENT_LAST_FRAME:0,KBLBS_PARSE_CONTENT_BITSTREAM_NOT_ENOUGH:-1,\\",128,0,0,0
.stabs "KBLBS_PARSE_CONTENT_ERR_FORMAT:-2,;",128,0,0,0
.stabs "22:T96=s16Version:14,0,16;Mode:14,16,16;Filter:14,32,16;Length:14,48,16;\\",128,0,0,0
.stabs "Timber:14,64,16;Pitch:14,80,16;Speed:14,96,16;HeadLength:14,112,16;;",128,0,0,0
.stabs "21:T97=eKBLBS_PARSE_HEAD_LAST_HEAD:0,KBLBS_PARSE_HEAD_FURTHERMORE_HEAD:1,\\",128,0,0,0
.stabs "KBLBS_PARSE_HEAD_ERR_VERSION:-1,KBLBS_PARSE_HEAD_ERR_MODE:-2,;",128,0,0,0
.stabs "20:T98=s10IMA_SR:14,0,16;IMA_ADPCM_BufSize:14,16,16;IMA_PCM_BufSize:14,32,16;\\",128,0,0,0
.stabs "IMA_Frame_No:11,48,32;;",128,0,0,0
.stabs "19:T99=eSMP_8K:1,SMP_16K:2,SMP_32K:3,SMP_11P025K:4,SMP_22P05K:5,SMP_44P1K:6,\\",128,0,0,0
.stabs "SMP_12K:7,SMP_24K:8,SMP_48K:9,;",128,0,0,0
.stabs "18:T100=eHead_Phone_Out:0,Speaker_Out:1,;",128,0,0,0
.stabs "17:T101=eNo_Mixed_To_DAC:0,Mixed_To_DAC:1,;",128,0,0,0
.stabs "16:T102=eMIC_In:0,Line_In:1,;",128,0,0,0
.stabs "15:T103=eMIC_Gain_0dB:0,MIC_Gain_20dB:1,;",128,0,0,0
.stabs "14:T104=eAUADC_Gain_0dB:0,AUADC_Gain_1P5dB:1,AUADC_Gain_3dB:2,AUADC_Gain_4P5dB:3,\\",128,0,0,0
.stabs "AUADC_Gain_6dB:4,AUADC_Gain_7P5dB:5,AUADC_Gain_9dB:6,AUADC_Gain_10P5dB:7,\\",128,0,0,0
.stabs "AUADC_Gain_12dB:8,AUADC_Gain_13P5dB:9,AUADC_Gain_15dB:10,AUADC_Gain_16P5dB:11,\\",128,0,0,0
.stabs "AUADC_Gain_18dB:12,AUADC_Gain_19P5dB:13,AUADC_Gain_21dB:14,AUADC_Gain_22P5dB:15,;",128,0,0,0
.stabs "13:T105=eAUADC_SAMPLE_RATE_96K:0,AUADC_SAMPLE_RATE_48K:1,AUADC_SAMPLE_RATE_44P1K:2,\\",128,0,0,0
.stabs "AUADC_SAMPLE_RATE_32K:3,AUADC_SAMPLE_RATE_24K:4,AUADC_SAMPLE_RATE_22P05K:5,\\",128,0,0,0
.stabs "AUADC_SAMPLE_RATE_16K:6,AUADC_SAMPLE_RATE_12K:7,AUADC_SAMPLE_RATE_11P025K:8,\\",128,0,0,0
.stabs "AUADC_SAMPLE_RATE_9P6K:9,AUADC_SAMPLE_RATE_8K:10,;",128,0,0,0
.stabs "12:T106=eAUADC_NO_ERR:0,AUADC_SampleRate_SETUP_ERR:-1,AUADC_DTU_SETUP_ERR:-2,\\",128,0,0,0
.stabs "AUADC_OUT_BUF_SETUP_ERR:-3,AUADC_BUF_SIZE_SETUP_ERR:-4,AUADC_CALL_BACK_SETUP_ERR:-5,\\",128,0,0,0
.stabs "AUADC_PARAMETER_SETUP_ERR:-6,AUADC_NO_INIT_ERR:-7,;",128,0,0,0
.stabs "11:T107=eDAC_SAMPLE_RATE_96K:0,DAC_SAMPLE_RATE_48K:1,DAC_SAMPLE_RATE_44P1K:2,\\",128,0,0,0
.stabs "DAC_SAMPLE_RATE_32K:3,DAC_SAMPLE_RATE_24K:4,DAC_SAMPLE_RATE_22P05K:5,DAC_SAMPLE_RATE_16K:6,\\",128,0,0,0
.stabs "DAC_SAMPLE_RATE_12K:7,DAC_SAMPLE_RATE_11P025K:8,DAC_SAMPLE_RATE_9P6K:9,DAC_SAMPLE_RATE_8K:10,;",128,0,0,0
.stabs "10:T108=eDAC_NO_ERR:0,DAC_SAMPLE_RATE_ERR:-1,DAC_NO_SET_FRAME_SIZE:-2,DAC_DTU_SETUP_ERR:-3,\\",128,0,0,0
.stabs "DAC_FRAME_SIZE_ERR:-4,DAC_NO_INIT:-5,DAC_PLL_SETUP_ERR:-6,DAC_SOCR_BIT15_DISABLE:-7,;",128,0,0,0
.stabs "9:T109=eUSB_UPLOAD:16,USB_DOWNLOAD:32,;",128,0,0,0
.stabs "8:T110=eREMOVABLE:128,FIXED:0,;",128,0,0,0
.stabs "7:T111=eDIRECT_ACCESS:0,CDROM:1280,;",128,0,0,0
.stabs "__STORAGE:T112=s38stor_status:113=*114=f1,0,32;stor_size:115=*116=f11,32,32;\\",128,0,0,0
.stabs "stor_read:117=*118=f1,64,32;stor_write:119=*120=f1,96,32;stor_check_wp:121=*122=f1,128,32;\\",128,0,0,0
.stabs "stor_flush:123=*124=f1,160,32;device_type:14,192,16;device_vendor:125=*2,208,32;\\",128,0,0,0
.stabs "device_identify:125,240,32;device_revision:125,272,32;;",128,0,0,0
.stabs "6:T126=eSPI_30M:0,SPI_20M:1,SPI_15M:2,SPI_12M:3,SPI_10M:4,SPI_7P5M:5,SPI_6M:6,\\",128,0,0,0
.stabs "SPI_4M:7,SPI_3M:8,SPI_2M:9,SPI_1M:10,SPI_750K:11,SPI_600K:12,SPI_400K:13,SPI_200K:14,\\",128,0,0,0
.stabs "SPI_100K:15,;",128,0,0,0
.stabs "5:T127=eSPIF_No_Err:0,Do_Not_Support:-1,Parameter_Error:-2,SPIF_No_Space:-3,\\",128,0,0,0
.stabs "Over_RES_Size:-4,Over_FAT_Size:-5,;",128,0,0,0
.stabs "4:T128=eSDTL_No_Err:0,Data_CRC_Err:-1,RSP_CRC_Err:-2,CMD_RSP_Timeout:-3,PRG_Timeout:-4,\\",128,0,0,0
.stabs "SD_Not_Ready_for_Data:-5,Write_Data_Err:-6,Erase_Addr_Err:-7,Erase_Block_No_Err:-8,\\",128,0,0,0
.stabs "Write_To_Protect_ERR:-9,Unusable_Card:-10,No_Card_Inserted:-11,SD_Over_RES_Size:-12,\\",128,0,0,0
.stabs "SD_Over_FAT_Size:-13,Unknown_Err:-14,;",128,0,0,0
.stabs "3:T129=eFEQ_60M:3,FEQ_48M:4,FEQ_40M:5,FEQ_34P28M:6,FEQ_30M:7,FEQ_26P66M:8,\\",128,0,0,0
.stabs "FEQ_24M:9,FEQ_20M:11,FEQ_16M:14,FEQ_15M:15,FEQ_12M:19,FEQ_10M:23,FEQ_9P6M:24,FEQ_8M:29,\\",128,0,0,0
.stabs "FEQ_7P5M:31,;",128,0,0,0
.stabs "2:T130=eDTU0:0,DTU1:1,DTU2:2,DTU3:3,;",128,0,0,0
.stabs "1:T131=eSET_FLASH_BUSY_TRAP:64,CLEAR_FLASH_BUSY_TRAP:65,NFC_DELAY_CALLBACK_TRAP:66,\\",128,0,0,0
.stabs "SD_DELAY_CALLBACK_TRAP:67,STORAGE_SET_BUSY:68,STORAGE_CLR_BUSY:69,Set_File_System_Busy:71,\\",128,0,0,0
.stabs "Clr_File_System_Busy:72,Is_CWrite_Protect:73,FS_Callback:74,GET_DATE_NTIME:75,\\",128,0,0,0
.stabs "I_Change_Drive:76,STACK_OVERFLOW_TRAP:4,STACK_UNDERFLOW_TRAP:8,EXCEPTION_TRAP:12,\\",128,0,0,0
.stabs "TIMER0_INT_TRAP:16,TIMER1_INT_TRAP:18,TIMER2_INT_TRAP:20,TIMER3_INT_TRAP:22,\\",128,0,0,0
.stabs "TIMER4_INT_TRAP:24,I2C_INT_TRAP:30,ADC_INT_TRAP:32,PORT_B_INT_TRAP:34,PORT_C_INT_TRAP:36,\\",128,0,0,0
.stabs "RTC_INT_TRAP:38,CSI_INT_TRAP:40,SPI2_INT_TRAP:42,SPI1_INT_TRAP:44,P80_INT_TRAP:53,\\",128,0,0,0
.stabs "UART_INT_TRAP:54,UART_TX_INT_TRAP:55,UART_RX_INT_TRAP:56,I2SL_INT_TRAP:58,I2SR_INT_TRAP:59,;",128,0,0,0
.stabs "_MP3_VBR_INFORMATION:t35",128,0,0,0
.stabs "_MP3_INFORMATION:t36",128,0,0,0
.stabs "_MP3_AUDIO_HANDLE:t44",128,0,0,0
.stabs "tID3v1TagStr:t43",128,0,0,0
.stabs "MP3API_STATUS:t51",128,0,0,0
.stabs "_MP3_AUDIO_STATUS:t42",128,0,0,0
.stabs "tAudioEQ:t52",128,0,0,0
.stabs "_MP3_AUDIO_EQINFO:t53",128,0,0,0
.stabs "tAudioErr:t55",128,0,0,0
.stabs "_bitref:t14",128,0,0,0
.stabs "GREV_BIT_NEW:t58",128,0,0,0
.stabs "ClusterListItem:t59",128,0,0,0
.stabs "Record:t60",128,0,0,0
.stabs "BOOKNEWS:t61",128,0,0,0
.stabs "LASTBOOK:t62",128,0,0,0
.stabs "DWord:t11",128,0,0,0
.stabs "Word:t14",128,0,0,0
.stabs "Int32:t6",128,0,0,0
.stabs "Int16:t1",128,0,0,0
.stabs "Int8:t2",128,0,0,0
.stabs "Uint32:t11",128,0,0,0
.stabs "Uint16:t14",128,0,0,0
.stabs "Byte:t10",128,0,0,0
.stabs "Uchar:t10",128,0,0,0
.stabs "Uint8:t10",128,0,0,0
.stabs "WORD:t14",128,0,0,0
.stabs "ULONG:t11",128,0,0,0
.stabs "USHORT:t14",128,0,0,0
.stabs "Dword:t11",128,0,0,0
.stabs "UCHAR:t10",128,0,0,0
.stabs "FP64:t3",128,0,0,0
.stabs "FP32:t4",128,0,0,0
.stabs "INT32S:t6",128,0,0,0
.stabs "INT32U:t11",128,0,0,0
.stabs "INT16S:t1",128,0,0,0
.stabs "INT16U:t14",128,0,0,0
.stabs "INT8S:t9",128,0,0,0
.stabs "INT8U:t10",128,0,0,0
.stabs "BOOLEAN:t10",128,0,0,0
.stabs "Union16:t63",128,0,0,0
.stabs "Union32:t65",128,0,0,0
.stabs "Status_bool:t10",128,0,0,0
.stabs "Status:t10",128,0,0,0
.stabs "Bool:t10",128,0,0,0
.stabs "S32:t6",128,0,0,0
.stabs "S16:t8",128,0,0,0
.stabs "S8:t9",128,0,0,0
.stabs "U32:t11",128,0,0,0
.stabs "U16:t13",128,0,0,0
.stabs "U8:t10",128,0,0,0
.stabs "Float16:t4",128,0,0,0
.stabs ":t132=*133=f15",128,4,0,0
.stabs "tStorageBusyCallBackFunc:t132",128,0,0,0
.stabs "tFSDrvHandle:t83",128,0,0,0
.stabs "FS_ENTRY_INFO:t86",128,0,0,0
.stabs "FAT_CACHE:t87",128,0,0,0
.stabs "FSINFO:t67",128,0,0,0
.stabs "FCFILE:t38",128,0,0,0
.stabs "FILE_INFO:t90",128,0,0,0
.stabs "FS_ERR:t82",128,0,0,0
.stabs "wchar_t:t13",128,0,0,0
.stabs "size_t:t11",128,0,0,0
.stabs "ptrdiff_t:t1",128,0,0,0
.stabs "tSDKLoadCodeStatus:t94",128,0,0,0
.stabs "tKBLBSParseContentStatus:t95",128,0,0,0
.stabs "tKBLBSHeadInfo:t96",128,0,0,0
.stabs "tKBLBSParseHeadStatus:t97",128,0,0,0
.stabs "tIMA_INFO:t98",128,0,0,0
.stabs "tMp3SampleRateID:t99",128,0,0,0
.stabs "tMixer_Out:t100",128,0,0,0
.stabs "tMixer_Option:t101",128,0,0,0
.stabs ":t134=*135=f15",128,4,0,0
.stabs "tAUADC_BufNotify:t134",128,0,0,0
.stabs "tAUADC_In_Path:t102",128,0,0,0
.stabs "tAUADC_MIC_Gain:t103",128,0,0,0
.stabs "tAUADC_Input_Gain:t104",128,0,0,0
.stabs "tAUADC_SmapleRate:t105",128,0,0,0
.stabs "tAUADC_Err:t106",128,0,0,0
.stabs "tDAC_SampleRate:t107",128,0,0,0
.stabs "tDAC_Error:t108",128,0,0,0
.stabs "_STORAGE:t112",128,0,0,0
.stabs ":t136=*137=f15",128,4,0,0
.stabs "tSPIFBusyCallBackFunc:t136",128,0,0,0
.stabs "tSPI_Clock:t126",128,0,0,0
.stabs "SPIF_ERR:t127",128,0,0,0
.stabs "SDTL_ERR:t128",128,0,0,0
.stabs ":t138=*139=f15",128,4,0,0
.stabs "PFWAKEUP:t138",128,0,0,0
.stabs "tFEQ:t129",128,0,0,0
.stabs "tKBDM9_DTUNumber:t130",128,0,0,0
.stabs "tKBDM9_TrapNo:t131",128,0,0,0

.area _$SYSTEM_C$(ROM,REL)
.stabs "", 100, 0, 0,Letext
Letext:

.area _SYSTEM_DATA$RD$flag_tishi(SYSTEM_DATA,REL,dat)
_flag_tishi::
	.ds 1
.stabs "flag_tishi:G10",32,0,4,0

.area _SYSTEM_DATA$RD$sleep_mode_count(SYSTEM_DATA,REL,dat)
.even
_sleep_mode_count::
	.ds 2
.stabs "sleep_mode_count:G14",32,0,4,0

.area _SYSTEM_DATA$RD$speaker_vol(SYSTEM_DATA,REL,dat)
.even
_speaker_vol::
	.ds 2
.stabs "speaker_vol:G14",32,0,4,0

.area _SYSTEM_DATA$RD$adc_timer(SYSTEM_DATA,REL,dat)
.even
_adc_timer::
	.ds 4
.stabs "adc_timer:G11",32,0,4,0

.area _SYSTEM_DATA$RD$adc_channel(SYSTEM_DATA,REL,dat)
_adc_channel::
	.ds 1
.stabs "adc_channel:G10",32,0,4,0

.area _SYSTEM_DATA$RD$led_timer(SYSTEM_DATA,REL,dat)
.even
_led_timer::
	.ds 4
.stabs "led_timer:G11",32,0,4,0
; EXTERN _SendString
; EXTERN _Get_ADCValue

.area _XRAM$RD$g_autopoweroff_timer(XRAM,REL,dat)
.even
_g_autopoweroff_timer::
	.ds 4
.stabs "g_autopoweroff_timer:G11",32,0,0,0

.area _XRAM$RD$g_b_poweroff_activated(XRAM,REL,dat)
_g_b_poweroff_activated::
	.ds 1
.stabs "g_b_poweroff_activated:G10",32,0,0,0

.area _XRAM$RD$g_b_autopoweroff_forbidden(XRAM,REL,dat)
_g_b_autopoweroff_forbidden::
	.ds 1
.stabs "g_b_autopoweroff_forbidden:G10",32,0,0,0

.area _XRAM$RD$Buf(XRAM,REL,dat)
_Buf::
	.ds 512
.stabs ":t140=ar1;0;511;10",128,0,0,0
.stabs "Buf:G140",32,0,0,0

.area _XRAM$RD$Length(XRAM,REL,dat)
.even
_Length::
	.ds 4
.stabs "Length:G11",32,0,0,0

.area _XRAM$RD$Start_Sector(XRAM,REL,dat)
.even
_Start_Sector::
	.ds 4
.stabs "Start_Sector:G11",32,0,0,0

.area _SYSTEM_DATA$RD$gOidXOR_Key(SYSTEM_DATA,REL,dat)
_gOidXOR_Key::
	.ds 1
.stabs "gOidXOR_Key:G10",32,0,4,0

.area _SYSTEM_DATA$RD$play_file_size(SYSTEM_DATA,REL,dat)
.even
_play_file_size::
	.ds 4
.stabs "play_file_size:G11",32,0,4,0

.area _SYSTEM_DATA$RD$mp3_begin_add(SYSTEM_DATA,REL,dat)
.even
_mp3_begin_add::
	.ds 4
.stabs "mp3_begin_add:G11",32,0,4,0

.area _SYSTEM_DATA$RD$ADPCM_File(SYSTEM_DATA,REL,dat)
.even
_ADPCM_File::
	.ds 2
.stabs "ADPCM_File:G65581",32,0,4,0

.area _SYSTEM_DATA$RD$flag_creat(SYSTEM_DATA,REL,dat)
_flag_creat::
	.ds 1
.stabs "flag_creat:G10",32,0,4,0

.area _SYSTEM_DATA$RD$OID_PLAY(SYSTEM_DATA,REL,dat)
_OID_PLAY::
	.ds 1
.stabs "OID_PLAY:G10",32,0,4,0

.area _SYSTEM_DATA$RD$low_num(SYSTEM_DATA,REL,dat)
.even
_low_num::
	.ds 2
.stabs "low_num:G14",32,0,4,0

.area _SYSTEM_DATA$RD$heigh_num(SYSTEM_DATA,REL,dat)
.even
_heigh_num::
	.ds 2
.stabs "heigh_num:G14",32,0,4,0

.area _SYSTEM_DATA$RD$system_check_timer(SYSTEM_DATA,REL,dat)
.even
_system_check_timer::
	.ds 4
.stabs "system_check_timer:G11",32,0,4,0

.area _SYSTEM_DATA$RD$DAC_Out(SYSTEM_DATA,REL,dat)
.even
_DAC_Out::
	.ds 2
.stabs "DAC_Out:G14",32,0,4,0

.area _SYSTEM_DATA$RD$flag_wav_play(SYSTEM_DATA,REL,dat)
_flag_wav_play::
	.ds 1
.stabs "flag_wav_play:G10",32,0,4,0

.area _SYSTEM_DATA$RD$battery_count(SYSTEM_DATA,REL,dat)
_battery_count::
	.ds 1
.stabs "battery_count:G10",32,0,4,0

.area _SYSTEM_DATA$RD$vol_idx_bak(SYSTEM_DATA,REL,dat)
.even
_vol_idx_bak::
	.ds 2
.stabs "vol_idx_bak:G14",32,0,4,0

.area _SYSTEM_DATA$RD$g_timer_tick(SYSTEM_DATA,REL,dat)
.even
_g_timer_tick::
	.ds 4
.stabs "g_timer_tick:G11",32,0,4,0

.area _SYSTEM_DATA$RD$g_system_clk_timer(SYSTEM_DATA,REL,dat)
.even
_g_system_clk_timer::
	.ds 4
.stabs "g_system_clk_timer:G11",32,0,4,0

.area _SYSTEM_DATA$RD$sleep_mode_timer(SYSTEM_DATA,REL,dat)
.even
_sleep_mode_timer::
	.ds 4
.stabs "sleep_mode_timer:G11",32,0,4,0

.area _SYSTEM_DATA$RD$qieqing_timer(SYSTEM_DATA,REL,dat)
.even
_qieqing_timer::
	.ds 4
.stabs "qieqing_timer:G11",32,0,4,0

.area _XRAM$RD$op_close_timer(XRAM,REL,dat)
.even
_op_close_timer::
	.ds 4
.stabs "op_close_timer:G11",32,0,0,0

.area _XRAM$RD$sys_led_timer(XRAM,REL,dat)
.even
_sys_led_timer::
	.ds 4
.stabs "sys_led_timer:G11",32,0,0,0

.area _XRAM$RD$rec_led_timer(XRAM,REL,dat)
.even
_rec_led_timer::
	.ds 4
.stabs "rec_led_timer:G11",32,0,0,0
; EXTERN _TM3ICR
; EXTERN _TM3PRD
; EXTERN _TMR3CR
; EXTERN _RTCWDT
; EXTERN _adc7_value
; EXTERN _adc3_value
; EXTERN _adc2_value
; EXTERN _adc0_value
; EXTERN _vol_idx
; EXTERN _sys_flag
; EXTERN _systerm_flag
; EXTERN _gflag
; EXTERN _DAC_Speaker_Volume
; EXTERN _DAC_HeadPhone_Volume
; EXTERN _DAC_Disable_Speaker
; EXTERN _DAC_Enable_HeadPhone
; EXTERN _SPIF_Set_Clock
; EXTERN _SetVector
; EXTERN _SystemClock

.area _BATTERY_CODE$RD$SYSTEM_C$(BATTERY_CODE,REL)
L400:
	.db 13
	.db 10
	;.asciz /low battery!/
	.db 108,111,119,32,98,97,116,116,101,114,121,33,0

.area _SYSTEM_CODE$RD$SYSTEM_C$(SYSTEM_CODE,REL)
L331:
	.db 13
	.db 10
	;.asciz /sys low!/
	.db 115,121,115,32,108,111,119,33,0

.area _SYSTEM_CODE$RD$SYSTEM_C$(SYSTEM_CODE,REL)
L313:
	.db 13
	.db 10
	;.asciz /sys up!/
	.db 115,121,115,32,117,112,33,0

.area _SYSTEM_CODE$RD$SYSTEM_C$(SYSTEM_CODE,REL)
L278:
	.db 13
	.db 10
	;.asciz /find usb!/
	.db 102,105,110,100,32,117,115,98,33,0

.area _SYSTEM_CODE$RD$SYSTEM_C$(SYSTEM_CODE,REL)
L45:
	.db 13
	.db 10
	;.asciz /system reset!/
	.db 115,121,115,116,101,109,32,114,101,115,101,116,33,0

; THE END
