; Generated by KBCC
.stabs "KBCC",0x3c,0,0,0
.stabs "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\UsbMassStoragev_TSD",0x64,0,3,Ltext0
.stabs "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\UsbMassStoragev_TSD\Src\USB_MassStorage_SD1.c",0x64,0,3,Ltext0

.area _$USB_MassStorage_SD1_c$(ROM,REL)
Ltext0:
.stabs "int:t1=r1;-32768;32767;",128,0,0,0
.stabs "char:t2=r2;-128;127;",128,0,0,0
.stabs "double:t3=r1;8;0;",128,0,0,0
.stabs "float:t4=r1;4;0;",128,0,0,0
.stabs "long double:t5=r1;8;0;",128,0,0,0
.stabs "long int:t6=r1;-2147483648;2147483647;",128,0,0,0
.stabs "long long int:t7=r1;-2147483648;2147483647;",128,0,0,0
.stabs "short:t8=r1;-32768;32767;",128,0,0,0
.stabs "signed char:t9=r1;-128;127;",128,0,0,0
.stabs "unsigned char:t10=r1;0;255;",128,0,0,0
.stabs "unsigned long:t11=r1;0;4294967295;",128,0,0,0
.stabs "unsigned long long:t12=r1;0;4294967295;",128,0,0,0
.stabs "unsigned short:t13=r1;0;65535;",128,0,0,0
.stabs "unsigned int:t14=r1;0;65535;",128,0,0,0
.stabs "void:t15=15",128,0,0,0
.stabs "short __fixed:t16=r1;2;0;",128,0,0,0
.stabs "__fixed:t17=r1;2;0;",128,0,0,0
.stabs "long __fixed:t18=r1;4;0;",128,0,0,0
.stabs "unsigned short __fixed:t19=r1;2;0;",128,0,0,0
.stabs "unsigned __fixed:t20=r1;2;0;",128,0,0,0
.stabs "unsigned long __fixed:t21=r1;4;0;",128,0,0,0
.stabs "__sat short __fixed:t22=r1;2;0;",128,0,0,0
.stabs "__sat __fixed:t23=r1;2;0;",128,0,0,0
.stabs "__sat long __fixed:t24=r1;4;0;",128,0,0,0
.stabs "__sat unsigned short __fixed:t25=r1;2;0;",128,0,0,0
.stabs "__sat unsigned __fixed:t26=r1;2;0;",128,0,0,0
.stabs "__sat unsigned long __fixed:t27=r1;4;0;",128,0,0,0
.stabs "short __accum:t28=r1;4;0;",128,0,0,0
.stabs "__accum:t29=r1;4;0;",128,0,0,0
.stabs "long __accum:t30=r1;6;0;",128,0,0,0
.stabs "unsigned short __accum:t31=r1;4;0;",128,0,0,0
.stabs "unsigned __accum:t32=r1;4;0;",128,0,0,0
.stabs "unsigned long __accum:t33=r1;6;0;",128,0,0,0
.include "kbccmacro.asm"
 .define _sdtl_mount	 _sd1_mount        
 .define _sdtl_resv_size	 _sd1_res_size     
 .define _sdtl_get_size	 _sd1_fat_size     
 .define _sdtl_resv_read	 _sd1_res_read     
 .define _sdtl_resv_write	 _sd1_res_write    
 .define _sdtl_read	 _sd1_read         
 .define _sdtl_write	 _sd1_write        
 .define _sdtl_cache_init	 _sd1_cache2k_init 
 .define _sdtl_cache_read	 _sd1_cache_read   
 .define _sdtl_cache_write _sd1_cache_write  
 .define _sdtl_cache_flush _sd1_cache_flush  
 .define _sdtl_allocate    _sd1_allocate     
 .define _spif_res_size	 _spif_resv_size   
 .define _spif_res_read	 _spif_resv_read   
 .define _spif_res_write	 _spif_resv_write  

.area _$usd1_protect(USB_MS_CODE,REL)
.stabs "usd1_protect:F1",36,0,4,_usd1_protect
_usd1_protect::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\UsbMassStoragev_TSD\Src\USB_MassStorage_SD1.c","usd1_protect",11
	LINK #0
.stabn 0xc0,0,0,L36-_usd1_protect
L36:
.stabn 0x44,0,12,L37-_usd1_protect
L37:
.stabn 0x44,0,13,L38-_usd1_protect
L38:
	MOV R0,#0
.stabn 0xe0,0,0,L39-_usd1_protect
L39:
.stabn 0x44,0,14,L40-_usd1_protect
L40:
L35:
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "usd1_write:F1",36,0,4,_usd1_write

.area _$usd1_write(USB_MS_CODE,REL)
_usd1_write::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\UsbMassStoragev_TSD\Src\USB_MassStorage_SD1.c","usd1_write",16
.stabs "Sector:p11",160,0,0,6
.stabs ":t34=*15",128,2,0,0
.stabs "Buf:p65570",160,0,0,10
	LINK #0
	PUSH R1
.stabn 0xc0,0,0,L42-_usd1_write
L42:
.stabn 0x44,0,17,L43-_usd1_write
L43:
.stabn 0x44,0,18,L44-_usd1_write
L44:
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _MassStorage_Write
.stabn 0x44,0,19,L45-_usd1_write
L45:
	MOV R0,[FP+#(10)]
	PUSH R0
	LOAD4$stack R0,R1,6,FP
	PUSH R1
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _sd1_cache_write
	ADD SP,#6
.stabn 0xe0,0,0,L46-_usd1_write
L46:
.stabn 0x44,0,20,L47-_usd1_write
L47:
L41:
	POP R1
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "usd1_status:F1",36,0,4,_usd1_status

.area _$usd1_status(USB_MS_CODE,REL)
_usd1_status::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\UsbMassStoragev_TSD\Src\USB_MassStorage_SD1.c","usd1_status",22
	LINK #0
.stabn 0xc0,0,0,L51-_usd1_status
L51:
.stabn 0x44,0,23,L52-_usd1_status
L52:
.stabn 0x44,0,24,L53-_usd1_status
L53:
	MOVX R0,_SD1_Mounted
	CMP R0,#0
	AJMP IF_EQ,L49
.stabn 0x44,0,25,L54-_usd1_status
L54:
	MOV R0,#1
	AJMP #0,L48
L49:
.stabn 0x44,0,27,L55-_usd1_status
L55:
	MOV R0,#0
.stabn 0xe0,0,0,L56-_usd1_status
L56:
.stabn 0x44,0,28,L57-_usd1_status
L57:
L48:
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "MassStorage_SD1_Register:F15",36,0,4,_MassStorage_SD1_Register

.area _$MassStorage_SD1_Register(USB_MS_CODE,REL)
_MassStorage_SD1_Register::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\UsbMassStoragev_TSD\Src\USB_MassStorage_SD1.c","MassStorage_SD1_Register",30
.stabs "lun:p1",160,0,0,6
	LINK #0
	PUSH R0
	PUSH R1
.stabn 0xc0,0,0,L62-_MassStorage_SD1_Register
L62:
.stabn 0x44,0,31,L63-_MassStorage_SD1_Register
L63:
.stabn 0x44,0,32,L64-_MassStorage_SD1_Register
L64:
	MOV R1,#(L61)
	MOV R0,#^(L61)
	PUSH R1
	PUSH R0
	MOV R1,#(L60)
	MOV R0,#^(L60)
	PUSH R1
	PUSH R0
	MOV R1,#(L59)
	MOV R0,#^(L59)
	PUSH R1
	PUSH R0
	MOV R0,#128
	PUSH R0
	MOV R1,#(_usd1_status)
	MOV R0,#^(_usd1_status)
	PUSH R1
	PUSH R0
	MOV R1,#(_sd1_fat_size)
	MOV R0,#^(_sd1_fat_size)
	PUSH R1
	PUSH R0
	MOV R1,#(_sd1_cache_flush)
	MOV R0,#^(_sd1_cache_flush)
	PUSH R1
	PUSH R0
	MOV R1,#(_usd1_protect)
	MOV R0,#^(_usd1_protect)
	PUSH R1
	PUSH R0
	MOV R1,#(_usd1_write)
	MOV R0,#^(_usd1_write)
	PUSH R1
	PUSH R0
	MOV R1,#(_sd1_cache_read)
	MOV R0,#^(_sd1_cache_read)
	PUSH R1
	PUSH R0
	MOV R0,[FP+#(6)]
	PUSH R0
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _USBStorageRegister
	ADD SP,#40
.stabn 0xe0,0,0,L65-_MassStorage_SD1_Register
L65:
.stabn 0x44,0,33,L66-_MassStorage_SD1_Register
L66:
L58:
	POP R1
	POP R0
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "MassStorage_SD1_Loop:F15",36,0,4,_MassStorage_SD1_Loop

.area _$MassStorage_SD1_Loop(USB_MS_CODE,REL)
_MassStorage_SD1_Loop::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\UsbMassStoragev_TSD\Src\USB_MassStorage_SD1.c","MassStorage_SD1_Loop",35
	LINK #0
.stabn 0xc0,0,0,L68-_MassStorage_SD1_Loop
L68:
.stabn 0x44,0,36,L69-_MassStorage_SD1_Loop
L69:
.stabn 0xe0,0,0,L70-_MassStorage_SD1_Loop
L70:
.stabn 0x44,0,38,L71-_MassStorage_SD1_Loop
L71:
L67:
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "MassStorage_SD1_Init:F15",36,0,4,_MassStorage_SD1_Init

.area _$MassStorage_SD1_Init(USB_MS_CODE,REL)
_MassStorage_SD1_Init::
.cfundef "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\UsbMassStoragev_TSD\Src\USB_MassStorage_SD1.c","MassStorage_SD1_Init",40
	LINK #0
	PUSH R0
.stabn 0xc0,0,0,L73-_MassStorage_SD1_Init
L73:
.stabn 0x44,0,41,L74-_MassStorage_SD1_Init
L74:
.stabn 0x44,0,42,L75-_MassStorage_SD1_Init
L75:
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _sd1_mount
.stabn 0x44,0,43,L76-_MassStorage_SD1_Init
L76:
	MOV R0,#3
	MOVX _SDCKCR,R0
.stabn 0x44,0,49,L77-_MassStorage_SD1_Init
L77:
.if KERNEL1_5 = 1
	CRIT #1
.endif
	SCALL _sd1_cache8k_init
.stabn 0xe0,0,0,L78-_MassStorage_SD1_Init
L78:
.stabn 0x44,0,53,L79-_MassStorage_SD1_Init
L79:
L72:
	POP R0
	UNLINK_MACRO
.if KERNEL1_5 = 1
	CRIT #1
.endif
	RETS
.stabs "34:T35=eHEADER_PHONE:0,SPEAKER:1,;",128,0,0,0
.stabs "33:T36=s2bRev0:14,0,1;bRev1:14,1,1;bRev2:14,2,1;bRev3:14,3,1;\\",128,0,0,0
.stabs "bRev4:14,4,1;bRev5:14,5,1;bRev6:14,6,1;bRev7:14,7,1;\\",128,0,0,0
.stabs "bRev8:14,8,1;bRev9:14,9,1;bRev10:14,10,1;bRev11:14,11,1;\\",128,0,0,0
.stabs "bRev12:14,12,1;bRev13:14,13,1;bRev14:14,14,1;bRev15:14,15,1;;",128,0,0,0
.stabs "32:T37=u2bits:36,0,16;value:13,0,16;;",128,0,0,0
.stabs "_ClusterListItem:T38=s18disk_id:13,0,16;start_cluster:11,16,32;\\",128,0,0,0
.stabs "offset_by_clus:11,48,32;cluster:11,80,32;seg_len:11,112,32;;",128,0,0,0
.stabs "31:T39=s8Ap3_num:13,0,16;Book_num:13,16,16;Page_num:13,32,16;\\",128,0,0,0
.stabs "Control_num:13,48,16;;",128,0,0,0
.stabs "30:T40=s4Cur_num:13,0,16;Max_num:13,16,16;;",128,0,0,0
.stabs "29:T41=s6Sd_num:13,0,16;Book_num:13,16,16;Book_id:13,32,16;;",128,0,0,0
.stabs "28:T42=u2w:13,0,16;b:43=ar1;0;1;10,0,16;;",128,0,0,0
.stabs "27:T44=u4dw:11,0,32;l:11,0,32;w:45=ar1;0;1;13,0,32;b:46=ar1;0;3;10,0,32;;",128,0,0,0
.stabs "_date_n_time:T47=s4year:14,0,7;month:14,7,4;day:14,11,5;\\",128,0,0,0
.stabs "hour:14,16,5;minute:14,21,6;second:14,27,5;;",128,0,0,0
.stabs "_fcb:T48=s86next:49=*48,0,16;used:1,16,16;spec:50=ar1;0;13;10,32,112;\\",128,0,0,0
.stabs "attribute:10,144,8;mode:10,152,8;date_n_time:47,160,32;sector_in_cluster:14,192,16;\\",128,0,0,0
.stabs "first_cluster:11,208,32;last_cluster:11,240,32;cluster:11,272,32;position:11,304,32;\\",128,0,0,0
.stabs "size:11,336,32;dir_cluster:11,368,32;dir_index:14,400,16;dir_first_cluster:11,416,32;\\",128,0,0,0
.stabs "fmode:14,448,16;possible_cluster:11,464,32;entry_index:14,496,16;lfn_cluster:11,512,32;\\",128,0,0,0
.stabs "old_final_cluster:11,544,32;new_start_cluster:11,576,32;pcluster_nodes:51=*14,608,32;\\",128,0,0,0
.stabs "node_count:14,640,16;skips_clusters:14,656,16;drive:1,672,16;;",128,0,0,0
.stabs "_fsinfo:T52=s134bytes_per_sector:14,0,16;sectors_per_cluster:14,16,16;\\",128,0,0,0
.stabs "num_of_fats:14,32,16;dir_entries:14,48,16;total_sectors:11,64,32;\\",128,0,0,0
.stabs "sectors_per_fat:11,96,32;media_id:10,128,8;dummy:10,136,8;first_fat_sector:11,144,32;\\",128,0,0,0
.stabs "first_dir_sector:11,176,32;first_dat_sector:11,208,32;max_cluster_num:11,240,32;\\",128,0,0,0
.stabs "last_cluster_mark:11,272,32;fs_semaphore:51,304,32;internal_slot:48,336,688;\\",128,0,0,0
.stabs "entry_ext:53=ar1;0;5;2,1024,48;;",128,0,0,0
.stabs "_drive:T54=s30drv_clear:55=*56=f1,0,32;drv_read:57=*58=f1,32,32;\\",128,0,0,0
.stabs "drv_write:59=*60=f1,64,32;drv_size:61=*62=f11,96,32;drv_flush:63=*64=f1,128,32;\\",128,0,0,0
.stabs "buffer:65=*10,160,16;sector_in_buffer:11,176,32;buffer_status:14,208,16;\\",128,0,0,0
.stabs "fsinfo:66=*52,224,16;;",128,0,0,0
.stabs "26:T68=s34Drv:54,0,240;pMountFunc:69=*70=f67=eFS_NO_ERROR:0,FS_DRIVE_ERROR:-1,\\",128,0,0,0
.stabs "FS_FORMAT_ERROR:-2,FS_SYSTEM_ERROR:-3,FS_INVALID_DIRECTORY:-4,FS_INVALID_SPEC:-5,\\",128,0,0,0
.stabs "FS_INVALID_MODE:-6,FS_FILE_NOT_FOUND:-7,FS_DIRECTORY_CONFLICT:-8,FS_DIRECTORY_FULL:-9,\\",128,0,0,0
.stabs "FS_OPENFILE_FULL:-10,FS_VOLUME_FULL:-11,FS_ACCESS_DENIED:-12,FS_SEEK_OUT_OF_RANGE:-13,\\",128,0,0,0
.stabs "FS_RENAMING_ERROR:-14,FS_UNRECOVERABLE_FILE:-15,FS_END_DIRECTORY:-16,FS_TRASH_ERROR:-17,\\",128,0,0,0
.stabs "FS_PARAMETER_ERROR:-18,FS_FILE_INCONSISTENT:-19,FS_WRITE_OUT_RANGE:-20,FS_TABLE_INCONSISTENT:-21,\\",128,0,0,0
.stabs "FS_DRIVE_NOT_READY:-22,FS_INVALID_CLUSTER:-23,;,240,32;;",128,0,0,0
.stabs "_fs_entry_info:T71=s2drive:1,0,16;;",128,0,0,0
.stabs "_fat_cache:T72=s12next:73=*72,0,32;drive:1,32,16;index:1,48,16;\\",128,0,0,0
.stabs "state:1,64,16;data:43,80,16;;",128,0,0,0
.stabs "_fc_trash_info:T74=s12first_cluster:11,0,32;cluster:11,32,32;index:1,64,16;\\",128,0,0,0
.stabs "secidx:1,80,16;;",128,0,0,0
.stabs "_file_info:T75=s280name:76=ar1;0;12;10,0,104;attribute:10,104,8;\\",128,0,0,0
.stabs "date_n_time:47,112,32;size:11,144,32;index:14,176,16;lfn:77=ar1;0;255;10,192,2048;;",128,0,0,0
.stabs "buffer_status:T78=eEMPTY:0,CLEAN:1,DIRTY:2,;",128,0,0,0
.stabs "24:T79=eSDKLOADCODE_NO_ERR:0,SDKLOADCODE_PARAM_ERR:-1,SDKLOADCODE_DATA_ERR:-5,;",128,0,0,0
.stabs "23:T80=eKBLBS_PARSE_CONTENT_OK:1,KBLBS_PARSE_CONTENT_LAST_FRAME:0,KBLBS_PARSE_CONTENT_BITSTREAM_NOT_ENOUGH:-1,\\",128,0,0,0
.stabs "KBLBS_PARSE_CONTENT_ERR_FORMAT:-2,;",128,0,0,0
.stabs "22:T81=s16Version:14,0,16;Mode:14,16,16;Filter:14,32,16;Length:14,48,16;\\",128,0,0,0
.stabs "Timber:14,64,16;Pitch:14,80,16;Speed:14,96,16;HeadLength:14,112,16;;",128,0,0,0
.stabs "21:T82=eKBLBS_PARSE_HEAD_LAST_HEAD:0,KBLBS_PARSE_HEAD_FURTHERMORE_HEAD:1,\\",128,0,0,0
.stabs "KBLBS_PARSE_HEAD_ERR_VERSION:-1,KBLBS_PARSE_HEAD_ERR_MODE:-2,;",128,0,0,0
.stabs "20:T83=s10IMA_SR:14,0,16;IMA_ADPCM_BufSize:14,16,16;IMA_PCM_BufSize:14,32,16;\\",128,0,0,0
.stabs "IMA_Frame_No:11,48,32;;",128,0,0,0
.stabs "19:T84=eSMP_8K:1,SMP_16K:2,SMP_32K:3,SMP_11P025K:4,SMP_22P05K:5,SMP_44P1K:6,\\",128,0,0,0
.stabs "SMP_12K:7,SMP_24K:8,SMP_48K:9,;",128,0,0,0
.stabs "18:T85=eHead_Phone_Out:0,Speaker_Out:1,;",128,0,0,0
.stabs "17:T86=eNo_Mixed_To_DAC:0,Mixed_To_DAC:1,;",128,0,0,0
.stabs "16:T87=eMIC_In:0,Line_In:1,;",128,0,0,0
.stabs "15:T88=eMIC_Gain_0dB:0,MIC_Gain_20dB:1,;",128,0,0,0
.stabs "14:T89=eAUADC_Gain_0dB:0,AUADC_Gain_1P5dB:1,AUADC_Gain_3dB:2,AUADC_Gain_4P5dB:3,\\",128,0,0,0
.stabs "AUADC_Gain_6dB:4,AUADC_Gain_7P5dB:5,AUADC_Gain_9dB:6,AUADC_Gain_10P5dB:7,\\",128,0,0,0
.stabs "AUADC_Gain_12dB:8,AUADC_Gain_13P5dB:9,AUADC_Gain_15dB:10,AUADC_Gain_16P5dB:11,\\",128,0,0,0
.stabs "AUADC_Gain_18dB:12,AUADC_Gain_19P5dB:13,AUADC_Gain_21dB:14,AUADC_Gain_22P5dB:15,;",128,0,0,0
.stabs "13:T90=eAUADC_SAMPLE_RATE_96K:0,AUADC_SAMPLE_RATE_48K:1,AUADC_SAMPLE_RATE_44P1K:2,\\",128,0,0,0
.stabs "AUADC_SAMPLE_RATE_32K:3,AUADC_SAMPLE_RATE_24K:4,AUADC_SAMPLE_RATE_22P05K:5,\\",128,0,0,0
.stabs "AUADC_SAMPLE_RATE_16K:6,AUADC_SAMPLE_RATE_12K:7,AUADC_SAMPLE_RATE_11P025K:8,\\",128,0,0,0
.stabs "AUADC_SAMPLE_RATE_9P6K:9,AUADC_SAMPLE_RATE_8K:10,;",128,0,0,0
.stabs "12:T91=eAUADC_NO_ERR:0,AUADC_SampleRate_SETUP_ERR:-1,AUADC_DTU_SETUP_ERR:-2,\\",128,0,0,0
.stabs "AUADC_OUT_BUF_SETUP_ERR:-3,AUADC_BUF_SIZE_SETUP_ERR:-4,AUADC_CALL_BACK_SETUP_ERR:-5,\\",128,0,0,0
.stabs "AUADC_PARAMETER_SETUP_ERR:-6,AUADC_NO_INIT_ERR:-7,;",128,0,0,0
.stabs "11:T92=eDAC_SAMPLE_RATE_96K:0,DAC_SAMPLE_RATE_48K:1,DAC_SAMPLE_RATE_44P1K:2,\\",128,0,0,0
.stabs "DAC_SAMPLE_RATE_32K:3,DAC_SAMPLE_RATE_24K:4,DAC_SAMPLE_RATE_22P05K:5,DAC_SAMPLE_RATE_16K:6,\\",128,0,0,0
.stabs "DAC_SAMPLE_RATE_12K:7,DAC_SAMPLE_RATE_11P025K:8,DAC_SAMPLE_RATE_9P6K:9,DAC_SAMPLE_RATE_8K:10,;",128,0,0,0
.stabs "10:T93=eDAC_NO_ERR:0,DAC_SAMPLE_RATE_ERR:-1,DAC_NO_SET_FRAME_SIZE:-2,DAC_DTU_SETUP_ERR:-3,\\",128,0,0,0
.stabs "DAC_FRAME_SIZE_ERR:-4,DAC_NO_INIT:-5,DAC_PLL_SETUP_ERR:-6,DAC_SOCR_BIT15_DISABLE:-7,;",128,0,0,0
.stabs "9:T94=eUSB_UPLOAD:16,USB_DOWNLOAD:32,;",128,0,0,0
.stabs "8:T95=eREMOVABLE:128,FIXED:0,;",128,0,0,0
.stabs "7:T96=eDIRECT_ACCESS:0,CDROM:1280,;",128,0,0,0
.stabs "__STORAGE:T97=s38stor_status:98=*99=f1,0,32;stor_size:100=*101=f11,32,32;\\",128,0,0,0
.stabs "stor_read:102=*103=f1,64,32;stor_write:104=*105=f1,96,32;stor_check_wp:106=*107=f1,128,32;\\",128,0,0,0
.stabs "stor_flush:108=*109=f1,160,32;device_type:14,192,16;device_vendor:110=*2,208,32;\\",128,0,0,0
.stabs "device_identify:110,240,32;device_revision:110,272,32;;",128,0,0,0
.stabs "6:T111=eSPI_30M:0,SPI_20M:1,SPI_15M:2,SPI_12M:3,SPI_10M:4,SPI_7P5M:5,SPI_6M:6,\\",128,0,0,0
.stabs "SPI_4M:7,SPI_3M:8,SPI_2M:9,SPI_1M:10,SPI_750K:11,SPI_600K:12,SPI_400K:13,SPI_200K:14,\\",128,0,0,0
.stabs "SPI_100K:15,;",128,0,0,0
.stabs "5:T112=eSPIF_No_Err:0,Do_Not_Support:-1,Parameter_Error:-2,SPIF_No_Space:-3,\\",128,0,0,0
.stabs "Over_RES_Size:-4,Over_FAT_Size:-5,;",128,0,0,0
.stabs "4:T113=eSDTL_No_Err:0,Data_CRC_Err:-1,RSP_CRC_Err:-2,CMD_RSP_Timeout:-3,PRG_Timeout:-4,\\",128,0,0,0
.stabs "SD_Not_Ready_for_Data:-5,Write_Data_Err:-6,Erase_Addr_Err:-7,Erase_Block_No_Err:-8,\\",128,0,0,0
.stabs "Write_To_Protect_ERR:-9,Unusable_Card:-10,No_Card_Inserted:-11,SD_Over_RES_Size:-12,\\",128,0,0,0
.stabs "SD_Over_FAT_Size:-13,Unknown_Err:-14,;",128,0,0,0
.stabs "3:T114=eFEQ_60M:3,FEQ_48M:4,FEQ_40M:5,FEQ_34P28M:6,FEQ_30M:7,FEQ_26P66M:8,\\",128,0,0,0
.stabs "FEQ_24M:9,FEQ_20M:11,FEQ_16M:14,FEQ_15M:15,FEQ_12M:19,FEQ_10M:23,FEQ_9P6M:24,FEQ_8M:29,\\",128,0,0,0
.stabs "FEQ_7P5M:31,;",128,0,0,0
.stabs "2:T115=eDTU0:0,DTU1:1,DTU2:2,DTU3:3,;",128,0,0,0
.stabs "1:T116=eSET_FLASH_BUSY_TRAP:64,CLEAR_FLASH_BUSY_TRAP:65,NFC_DELAY_CALLBACK_TRAP:66,\\",128,0,0,0
.stabs "SD_DELAY_CALLBACK_TRAP:67,STORAGE_SET_BUSY:68,STORAGE_CLR_BUSY:69,Set_File_System_Busy:71,\\",128,0,0,0
.stabs "Clr_File_System_Busy:72,Is_CWrite_Protect:73,FS_Callback:74,GET_DATE_NTIME:75,\\",128,0,0,0
.stabs "I_Change_Drive:76,STACK_OVERFLOW_TRAP:4,STACK_UNDERFLOW_TRAP:8,EXCEPTION_TRAP:12,\\",128,0,0,0
.stabs "TIMER0_INT_TRAP:16,TIMER1_INT_TRAP:18,TIMER2_INT_TRAP:20,TIMER3_INT_TRAP:22,\\",128,0,0,0
.stabs "TIMER4_INT_TRAP:24,I2C_INT_TRAP:30,ADC_INT_TRAP:32,PORT_B_INT_TRAP:34,PORT_C_INT_TRAP:36,\\",128,0,0,0
.stabs "RTC_INT_TRAP:38,CSI_INT_TRAP:40,SPI2_INT_TRAP:42,SPI1_INT_TRAP:44,P80_INT_TRAP:53,\\",128,0,0,0
.stabs "UART_INT_TRAP:54,UART_TX_INT_TRAP:55,UART_RX_INT_TRAP:56,I2SL_INT_TRAP:58,I2SR_INT_TRAP:59,;",128,0,0,0
.stabs "GREV_BIT_NEW:t37",128,0,0,0
.stabs "ClusterListItem:t38",128,0,0,0
.stabs "Record:t39",128,0,0,0
.stabs "BOOKNEWS:t40",128,0,0,0
.stabs "LASTBOOK:t41",128,0,0,0
.stabs "DWord:t11",128,0,0,0
.stabs "Word:t14",128,0,0,0
.stabs "Int32:t6",128,0,0,0
.stabs "Int16:t1",128,0,0,0
.stabs "Int8:t2",128,0,0,0
.stabs "Uint32:t11",128,0,0,0
.stabs "Uint16:t14",128,0,0,0
.stabs "Byte:t10",128,0,0,0
.stabs "Uchar:t10",128,0,0,0
.stabs "Uint8:t10",128,0,0,0
.stabs "WORD:t14",128,0,0,0
.stabs "ULONG:t11",128,0,0,0
.stabs "USHORT:t14",128,0,0,0
.stabs "Dword:t11",128,0,0,0
.stabs "UCHAR:t10",128,0,0,0
.stabs "FP64:t3",128,0,0,0
.stabs "FP32:t4",128,0,0,0
.stabs "INT32S:t6",128,0,0,0
.stabs "INT32U:t11",128,0,0,0
.stabs "INT16S:t1",128,0,0,0
.stabs "INT16U:t14",128,0,0,0
.stabs "INT8S:t9",128,0,0,0
.stabs "INT8U:t10",128,0,0,0
.stabs "BOOLEAN:t10",128,0,0,0
.stabs "Union16:t42",128,0,0,0
.stabs "Union32:t44",128,0,0,0
.stabs "Status_bool:t10",128,0,0,0
.stabs "Status:t10",128,0,0,0
.stabs "Bool:t10",128,0,0,0
.stabs "S32:t6",128,0,0,0
.stabs "S16:t8",128,0,0,0
.stabs "S8:t9",128,0,0,0
.stabs "U32:t11",128,0,0,0
.stabs "U16:t13",128,0,0,0
.stabs "U8:t10",128,0,0,0
.stabs "Float16:t4",128,0,0,0
.stabs ":t117=*118=f15",128,4,0,0
.stabs "tStorageBusyCallBackFunc:t117",128,0,0,0
.stabs "tFSDrvHandle:t68",128,0,0,0
.stabs "FS_ENTRY_INFO:t71",128,0,0,0
.stabs "FAT_CACHE:t72",128,0,0,0
.stabs "FSINFO:t52",128,0,0,0
.stabs "FCFILE:t48",128,0,0,0
.stabs "FILE_INFO:t75",128,0,0,0
.stabs "FS_ERR:t67",128,0,0,0
.stabs "wchar_t:t13",128,0,0,0
.stabs "size_t:t11",128,0,0,0
.stabs "ptrdiff_t:t1",128,0,0,0
.stabs "tSDKLoadCodeStatus:t79",128,0,0,0
.stabs "tKBLBSParseContentStatus:t80",128,0,0,0
.stabs "tKBLBSHeadInfo:t81",128,0,0,0
.stabs "tKBLBSParseHeadStatus:t82",128,0,0,0
.stabs "tIMA_INFO:t83",128,0,0,0
.stabs "tMp3SampleRateID:t84",128,0,0,0
.stabs "tMixer_Out:t85",128,0,0,0
.stabs "tMixer_Option:t86",128,0,0,0
.stabs ":t119=*120=f15",128,4,0,0
.stabs "tAUADC_BufNotify:t119",128,0,0,0
.stabs "tAUADC_In_Path:t87",128,0,0,0
.stabs "tAUADC_MIC_Gain:t88",128,0,0,0
.stabs "tAUADC_Input_Gain:t89",128,0,0,0
.stabs "tAUADC_SmapleRate:t90",128,0,0,0
.stabs "tAUADC_Err:t91",128,0,0,0
.stabs "tDAC_SampleRate:t92",128,0,0,0
.stabs "tDAC_Error:t93",128,0,0,0
.stabs "_STORAGE:t97",128,0,0,0
.stabs ":t121=*122=f15",128,4,0,0
.stabs "tSPIFBusyCallBackFunc:t121",128,0,0,0
.stabs "tSPI_Clock:t111",128,0,0,0
.stabs "SPIF_ERR:t112",128,0,0,0
.stabs "SDTL_ERR:t113",128,0,0,0
.stabs ":t123=*124=f15",128,4,0,0
.stabs "PFWAKEUP:t123",128,0,0,0
.stabs "tFEQ:t114",128,0,0,0
.stabs "tKBDM9_DTUNumber:t115",128,0,0,0
.stabs "tKBDM9_TrapNo:t116",128,0,0,0
.stabs "_bitref:t14",128,0,0,0

.area _$USB_MassStorage_SD1_c$(ROM,REL)
.stabs "", 100, 0, 0,Letext
Letext:
; EXTERN _MassStorage_Write
; EXTERN _USBStorageRegister
; EXTERN _sd1_cache_flush
; EXTERN _sd1_cache_write
; EXTERN _sd1_cache_read
; EXTERN _sd1_cache8k_init
; EXTERN _sd1_fat_size
; EXTERN _sd1_mount
; EXTERN _SD1_Mounted
; EXTERN _SDCKCR

.area _USB_MS_CODE$RD$USB_MassStorage_SD1_c$(USB_MS_CODE,REL)
L61:
	;.asciz /1.00/
	.db 49,46,48,48,0

.area _USB_MS_CODE$RD$USB_MassStorage_SD1_c$(USB_MS_CODE,REL)
L60:
	;.asciz /SD-1 Disk/
	.db 83,68,45,49,32,68,105,115,107,0

.area _USB_MS_CODE$RD$USB_MassStorage_SD1_c$(USB_MS_CODE,REL)
L59:
	;.asciz /KB USB20/
	.db 75,66,32,85,83,66,50,48,0

; THE END
