; Generated by KBCC
.stabs "KBCC",0x3c,0,0,0
.stabs "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\UsbMassStoragev_TSD",0x64,0,3,Ltext0
.stabs "E:\work\kb\code\80VT\80VT(20160918)t1\Fw\UsbMassStoragev_TSD\Src\USB_MassStorage_UGP.c",0x64,0,3,Ltext0

.area _$USB_MassStorage_UGP_c$(ROM,REL)
Ltext0:
.stabs "int:t1=r1;-32768;32767;",128,0,0,0
.stabs "char:t2=r2;-128;127;",128,0,0,0
.stabs "double:t3=r1;8;0;",128,0,0,0
.stabs "float:t4=r1;4;0;",128,0,0,0
.stabs "long double:t5=r1;8;0;",128,0,0,0
.stabs "long int:t6=r1;-2147483648;2147483647;",128,0,0,0
.stabs "long long int:t7=r1;-2147483648;2147483647;",128,0,0,0
.stabs "short:t8=r1;-32768;32767;",128,0,0,0
.stabs "signed char:t9=r1;-128;127;",128,0,0,0
.stabs "unsigned char:t10=r1;0;255;",128,0,0,0
.stabs "unsigned long:t11=r1;0;4294967295;",128,0,0,0
.stabs "unsigned long long:t12=r1;0;4294967295;",128,0,0,0
.stabs "unsigned short:t13=r1;0;65535;",128,0,0,0
.stabs "unsigned int:t14=r1;0;65535;",128,0,0,0
.stabs "void:t15=15",128,0,0,0
.stabs "short __fixed:t16=r1;2;0;",128,0,0,0
.stabs "__fixed:t17=r1;2;0;",128,0,0,0
.stabs "long __fixed:t18=r1;4;0;",128,0,0,0
.stabs "unsigned short __fixed:t19=r1;2;0;",128,0,0,0
.stabs "unsigned __fixed:t20=r1;2;0;",128,0,0,0
.stabs "unsigned long __fixed:t21=r1;4;0;",128,0,0,0
.stabs "__sat short __fixed:t22=r1;2;0;",128,0,0,0
.stabs "__sat __fixed:t23=r1;2;0;",128,0,0,0
.stabs "__sat long __fixed:t24=r1;4;0;",128,0,0,0
.stabs "__sat unsigned short __fixed:t25=r1;2;0;",128,0,0,0
.stabs "__sat unsigned __fixed:t26=r1;2;0;",128,0,0,0
.stabs "__sat unsigned long __fixed:t27=r1;4;0;",128,0,0,0
.stabs "short __accum:t28=r1;4;0;",128,0,0,0
.stabs "__accum:t29=r1;4;0;",128,0,0,0
.stabs "long __accum:t30=r1;6;0;",128,0,0,0
.stabs "unsigned short __accum:t31=r1;4;0;",128,0,0,0
.stabs "unsigned __accum:t32=r1;4;0;",128,0,0,0
.stabs "unsigned long __accum:t33=r1;6;0;",128,0,0,0
.include "kbccmacro.asm"
 .define _sdtl_mount	 _sd1_mount        
 .define _sdtl_resv_size	 _sd1_res_size     
 .define _sdtl_get_size	 _sd1_fat_size     
 .define _sdtl_resv_read	 _sd1_res_read     
 .define _sdtl_resv_write	 _sd1_res_write    
 .define _sdtl_read	 _sd1_read         
 .define _sdtl_write	 _sd1_write        
 .define _sdtl_cache_init	 _sd1_cache2k_init 
 .define _sdtl_cache_read	 _sd1_cache_read   
 .define _sdtl_cache_write _sd1_cache_write  
 .define _sdtl_cache_flush _sd1_cache_flush  
 .define _sdtl_allocate    _sd1_allocate     
 .define _spif_res_size	 _spif_resv_size   
 .define _spif_res_read	 _spif_resv_read   
 .define _spif_res_write	 _spif_resv_write  
.stabs "34:T34=eHEADER_PHONE:0,SPEAKER:1,;",128,0,0,0
.stabs "33:T35=s2bRev0:14,0,1;bRev1:14,1,1;bRev2:14,2,1;bRev3:14,3,1;\\",128,0,0,0
.stabs "bRev4:14,4,1;bRev5:14,5,1;bRev6:14,6,1;bRev7:14,7,1;\\",128,0,0,0
.stabs "bRev8:14,8,1;bRev9:14,9,1;bRev10:14,10,1;bRev11:14,11,1;\\",128,0,0,0
.stabs "bRev12:14,12,1;bRev13:14,13,1;bRev14:14,14,1;bRev15:14,15,1;;",128,0,0,0
.stabs "32:T36=u2bits:35,0,16;value:13,0,16;;",128,0,0,0
.stabs "_ClusterListItem:T37=s18disk_id:13,0,16;start_cluster:11,16,32;\\",128,0,0,0
.stabs "offset_by_clus:11,48,32;cluster:11,80,32;seg_len:11,112,32;;",128,0,0,0
.stabs "31:T38=s8Ap3_num:13,0,16;Book_num:13,16,16;Page_num:13,32,16;\\",128,0,0,0
.stabs "Control_num:13,48,16;;",128,0,0,0
.stabs "30:T39=s4Cur_num:13,0,16;Max_num:13,16,16;;",128,0,0,0
.stabs "29:T40=s6Sd_num:13,0,16;Book_num:13,16,16;Book_id:13,32,16;;",128,0,0,0
.stabs "28:T41=u2w:13,0,16;b:42=ar1;0;1;10,0,16;;",128,0,0,0
.stabs "27:T43=u4dw:11,0,32;l:11,0,32;w:44=ar1;0;1;13,0,32;b:45=ar1;0;3;10,0,32;;",128,0,0,0
.stabs "_date_n_time:T46=s4year:14,0,7;month:14,7,4;day:14,11,5;\\",128,0,0,0
.stabs "hour:14,16,5;minute:14,21,6;second:14,27,5;;",128,0,0,0
.stabs "_fcb:T47=s86next:48=*47,0,16;used:1,16,16;spec:49=ar1;0;13;10,32,112;\\",128,0,0,0
.stabs "attribute:10,144,8;mode:10,152,8;date_n_time:46,160,32;sector_in_cluster:14,192,16;\\",128,0,0,0
.stabs "first_cluster:11,208,32;last_cluster:11,240,32;cluster:11,272,32;position:11,304,32;\\",128,0,0,0
.stabs "size:11,336,32;dir_cluster:11,368,32;dir_index:14,400,16;dir_first_cluster:11,416,32;\\",128,0,0,0
.stabs "fmode:14,448,16;possible_cluster:11,464,32;entry_index:14,496,16;lfn_cluster:11,512,32;\\",128,0,0,0
.stabs "old_final_cluster:11,544,32;new_start_cluster:11,576,32;pcluster_nodes:50=*14,608,32;\\",128,0,0,0
.stabs "node_count:14,640,16;skips_clusters:14,656,16;drive:1,672,16;;",128,0,0,0
.stabs "_fsinfo:T51=s134bytes_per_sector:14,0,16;sectors_per_cluster:14,16,16;\\",128,0,0,0
.stabs "num_of_fats:14,32,16;dir_entries:14,48,16;total_sectors:11,64,32;\\",128,0,0,0
.stabs "sectors_per_fat:11,96,32;media_id:10,128,8;dummy:10,136,8;first_fat_sector:11,144,32;\\",128,0,0,0
.stabs "first_dir_sector:11,176,32;first_dat_sector:11,208,32;max_cluster_num:11,240,32;\\",128,0,0,0
.stabs "last_cluster_mark:11,272,32;fs_semaphore:50,304,32;internal_slot:47,336,688;\\",128,0,0,0
.stabs "entry_ext:52=ar1;0;5;2,1024,48;;",128,0,0,0
.stabs "_drive:T53=s30drv_clear:54=*55=f1,0,32;drv_read:56=*57=f1,32,32;\\",128,0,0,0
.stabs "drv_write:58=*59=f1,64,32;drv_size:60=*61=f11,96,32;drv_flush:62=*63=f1,128,32;\\",128,0,0,0
.stabs "buffer:64=*10,160,16;sector_in_buffer:11,176,32;buffer_status:14,208,16;\\",128,0,0,0
.stabs "fsinfo:65=*51,224,16;;",128,0,0,0
.stabs "26:T67=s34Drv:53,0,240;pMountFunc:68=*69=f66=eFS_NO_ERROR:0,FS_DRIVE_ERROR:-1,\\",128,0,0,0
.stabs "FS_FORMAT_ERROR:-2,FS_SYSTEM_ERROR:-3,FS_INVALID_DIRECTORY:-4,FS_INVALID_SPEC:-5,\\",128,0,0,0
.stabs "FS_INVALID_MODE:-6,FS_FILE_NOT_FOUND:-7,FS_DIRECTORY_CONFLICT:-8,FS_DIRECTORY_FULL:-9,\\",128,0,0,0
.stabs "FS_OPENFILE_FULL:-10,FS_VOLUME_FULL:-11,FS_ACCESS_DENIED:-12,FS_SEEK_OUT_OF_RANGE:-13,\\",128,0,0,0
.stabs "FS_RENAMING_ERROR:-14,FS_UNRECOVERABLE_FILE:-15,FS_END_DIRECTORY:-16,FS_TRASH_ERROR:-17,\\",128,0,0,0
.stabs "FS_PARAMETER_ERROR:-18,FS_FILE_INCONSISTENT:-19,FS_WRITE_OUT_RANGE:-20,FS_TABLE_INCONSISTENT:-21,\\",128,0,0,0
.stabs "FS_DRIVE_NOT_READY:-22,FS_INVALID_CLUSTER:-23,;,240,32;;",128,0,0,0
.stabs "_fs_entry_info:T70=s2drive:1,0,16;;",128,0,0,0
.stabs "_fat_cache:T71=s12next:72=*71,0,32;drive:1,32,16;index:1,48,16;\\",128,0,0,0
.stabs "state:1,64,16;data:42,80,16;;",128,0,0,0
.stabs "_fc_trash_info:T73=s12first_cluster:11,0,32;cluster:11,32,32;index:1,64,16;\\",128,0,0,0
.stabs "secidx:1,80,16;;",128,0,0,0
.stabs "_file_info:T74=s280name:75=ar1;0;12;10,0,104;attribute:10,104,8;\\",128,0,0,0
.stabs "date_n_time:46,112,32;size:11,144,32;index:14,176,16;lfn:76=ar1;0;255;10,192,2048;;",128,0,0,0
.stabs "buffer_status:T77=eEMPTY:0,CLEAN:1,DIRTY:2,;",128,0,0,0
.stabs "24:T78=eSDKLOADCODE_NO_ERR:0,SDKLOADCODE_PARAM_ERR:-1,SDKLOADCODE_DATA_ERR:-5,;",128,0,0,0
.stabs "23:T79=eKBLBS_PARSE_CONTENT_OK:1,KBLBS_PARSE_CONTENT_LAST_FRAME:0,KBLBS_PARSE_CONTENT_BITSTREAM_NOT_ENOUGH:-1,\\",128,0,0,0
.stabs "KBLBS_PARSE_CONTENT_ERR_FORMAT:-2,;",128,0,0,0
.stabs "22:T80=s16Version:14,0,16;Mode:14,16,16;Filter:14,32,16;Length:14,48,16;\\",128,0,0,0
.stabs "Timber:14,64,16;Pitch:14,80,16;Speed:14,96,16;HeadLength:14,112,16;;",128,0,0,0
.stabs "21:T81=eKBLBS_PARSE_HEAD_LAST_HEAD:0,KBLBS_PARSE_HEAD_FURTHERMORE_HEAD:1,\\",128,0,0,0
.stabs "KBLBS_PARSE_HEAD_ERR_VERSION:-1,KBLBS_PARSE_HEAD_ERR_MODE:-2,;",128,0,0,0
.stabs "20:T82=s10IMA_SR:14,0,16;IMA_ADPCM_BufSize:14,16,16;IMA_PCM_BufSize:14,32,16;\\",128,0,0,0
.stabs "IMA_Frame_No:11,48,32;;",128,0,0,0
.stabs "19:T83=eSMP_8K:1,SMP_16K:2,SMP_32K:3,SMP_11P025K:4,SMP_22P05K:5,SMP_44P1K:6,\\",128,0,0,0
.stabs "SMP_12K:7,SMP_24K:8,SMP_48K:9,;",128,0,0,0
.stabs "18:T84=eHead_Phone_Out:0,Speaker_Out:1,;",128,0,0,0
.stabs "17:T85=eNo_Mixed_To_DAC:0,Mixed_To_DAC:1,;",128,0,0,0
.stabs "16:T86=eMIC_In:0,Line_In:1,;",128,0,0,0
.stabs "15:T87=eMIC_Gain_0dB:0,MIC_Gain_20dB:1,;",128,0,0,0
.stabs "14:T88=eAUADC_Gain_0dB:0,AUADC_Gain_1P5dB:1,AUADC_Gain_3dB:2,AUADC_Gain_4P5dB:3,\\",128,0,0,0
.stabs "AUADC_Gain_6dB:4,AUADC_Gain_7P5dB:5,AUADC_Gain_9dB:6,AUADC_Gain_10P5dB:7,\\",128,0,0,0
.stabs "AUADC_Gain_12dB:8,AUADC_Gain_13P5dB:9,AUADC_Gain_15dB:10,AUADC_Gain_16P5dB:11,\\",128,0,0,0
.stabs "AUADC_Gain_18dB:12,AUADC_Gain_19P5dB:13,AUADC_Gain_21dB:14,AUADC_Gain_22P5dB:15,;",128,0,0,0
.stabs "13:T89=eAUADC_SAMPLE_RATE_96K:0,AUADC_SAMPLE_RATE_48K:1,AUADC_SAMPLE_RATE_44P1K:2,\\",128,0,0,0
.stabs "AUADC_SAMPLE_RATE_32K:3,AUADC_SAMPLE_RATE_24K:4,AUADC_SAMPLE_RATE_22P05K:5,\\",128,0,0,0
.stabs "AUADC_SAMPLE_RATE_16K:6,AUADC_SAMPLE_RATE_12K:7,AUADC_SAMPLE_RATE_11P025K:8,\\",128,0,0,0
.stabs "AUADC_SAMPLE_RATE_9P6K:9,AUADC_SAMPLE_RATE_8K:10,;",128,0,0,0
.stabs "12:T90=eAUADC_NO_ERR:0,AUADC_SampleRate_SETUP_ERR:-1,AUADC_DTU_SETUP_ERR:-2,\\",128,0,0,0
.stabs "AUADC_OUT_BUF_SETUP_ERR:-3,AUADC_BUF_SIZE_SETUP_ERR:-4,AUADC_CALL_BACK_SETUP_ERR:-5,\\",128,0,0,0
.stabs "AUADC_PARAMETER_SETUP_ERR:-6,AUADC_NO_INIT_ERR:-7,;",128,0,0,0
.stabs "11:T91=eDAC_SAMPLE_RATE_96K:0,DAC_SAMPLE_RATE_48K:1,DAC_SAMPLE_RATE_44P1K:2,\\",128,0,0,0
.stabs "DAC_SAMPLE_RATE_32K:3,DAC_SAMPLE_RATE_24K:4,DAC_SAMPLE_RATE_22P05K:5,DAC_SAMPLE_RATE_16K:6,\\",128,0,0,0
.stabs "DAC_SAMPLE_RATE_12K:7,DAC_SAMPLE_RATE_11P025K:8,DAC_SAMPLE_RATE_9P6K:9,DAC_SAMPLE_RATE_8K:10,;",128,0,0,0
.stabs "10:T92=eDAC_NO_ERR:0,DAC_SAMPLE_RATE_ERR:-1,DAC_NO_SET_FRAME_SIZE:-2,DAC_DTU_SETUP_ERR:-3,\\",128,0,0,0
.stabs "DAC_FRAME_SIZE_ERR:-4,DAC_NO_INIT:-5,DAC_PLL_SETUP_ERR:-6,DAC_SOCR_BIT15_DISABLE:-7,;",128,0,0,0
.stabs "9:T93=eUSB_UPLOAD:16,USB_DOWNLOAD:32,;",128,0,0,0
.stabs "8:T94=eREMOVABLE:128,FIXED:0,;",128,0,0,0
.stabs "7:T95=eDIRECT_ACCESS:0,CDROM:1280,;",128,0,0,0
.stabs "__STORAGE:T96=s38stor_status:97=*98=f1,0,32;stor_size:99=*100=f11,32,32;\\",128,0,0,0
.stabs "stor_read:101=*102=f1,64,32;stor_write:103=*104=f1,96,32;stor_check_wp:105=*106=f1,128,32;\\",128,0,0,0
.stabs "stor_flush:107=*108=f1,160,32;device_type:14,192,16;device_vendor:109=*2,208,32;\\",128,0,0,0
.stabs "device_identify:109,240,32;device_revision:109,272,32;;",128,0,0,0
.stabs "6:T110=eSPI_30M:0,SPI_20M:1,SPI_15M:2,SPI_12M:3,SPI_10M:4,SPI_7P5M:5,SPI_6M:6,\\",128,0,0,0
.stabs "SPI_4M:7,SPI_3M:8,SPI_2M:9,SPI_1M:10,SPI_750K:11,SPI_600K:12,SPI_400K:13,SPI_200K:14,\\",128,0,0,0
.stabs "SPI_100K:15,;",128,0,0,0
.stabs "5:T111=eSPIF_No_Err:0,Do_Not_Support:-1,Parameter_Error:-2,SPIF_No_Space:-3,\\",128,0,0,0
.stabs "Over_RES_Size:-4,Over_FAT_Size:-5,;",128,0,0,0
.stabs "4:T112=eSDTL_No_Err:0,Data_CRC_Err:-1,RSP_CRC_Err:-2,CMD_RSP_Timeout:-3,PRG_Timeout:-4,\\",128,0,0,0
.stabs "SD_Not_Ready_for_Data:-5,Write_Data_Err:-6,Erase_Addr_Err:-7,Erase_Block_No_Err:-8,\\",128,0,0,0
.stabs "Write_To_Protect_ERR:-9,Unusable_Card:-10,No_Card_Inserted:-11,SD_Over_RES_Size:-12,\\",128,0,0,0
.stabs "SD_Over_FAT_Size:-13,Unknown_Err:-14,;",128,0,0,0
.stabs "3:T113=eFEQ_60M:3,FEQ_48M:4,FEQ_40M:5,FEQ_34P28M:6,FEQ_30M:7,FEQ_26P66M:8,\\",128,0,0,0
.stabs "FEQ_24M:9,FEQ_20M:11,FEQ_16M:14,FEQ_15M:15,FEQ_12M:19,FEQ_10M:23,FEQ_9P6M:24,FEQ_8M:29,\\",128,0,0,0
.stabs "FEQ_7P5M:31,;",128,0,0,0
.stabs "2:T114=eDTU0:0,DTU1:1,DTU2:2,DTU3:3,;",128,0,0,0
.stabs "1:T115=eSET_FLASH_BUSY_TRAP:64,CLEAR_FLASH_BUSY_TRAP:65,NFC_DELAY_CALLBACK_TRAP:66,\\",128,0,0,0
.stabs "SD_DELAY_CALLBACK_TRAP:67,STORAGE_SET_BUSY:68,STORAGE_CLR_BUSY:69,Set_File_System_Busy:71,\\",128,0,0,0
.stabs "Clr_File_System_Busy:72,Is_CWrite_Protect:73,FS_Callback:74,GET_DATE_NTIME:75,\\",128,0,0,0
.stabs "I_Change_Drive:76,STACK_OVERFLOW_TRAP:4,STACK_UNDERFLOW_TRAP:8,EXCEPTION_TRAP:12,\\",128,0,0,0
.stabs "TIMER0_INT_TRAP:16,TIMER1_INT_TRAP:18,TIMER2_INT_TRAP:20,TIMER3_INT_TRAP:22,\\",128,0,0,0
.stabs "TIMER4_INT_TRAP:24,I2C_INT_TRAP:30,ADC_INT_TRAP:32,PORT_B_INT_TRAP:34,PORT_C_INT_TRAP:36,\\",128,0,0,0
.stabs "RTC_INT_TRAP:38,CSI_INT_TRAP:40,SPI2_INT_TRAP:42,SPI1_INT_TRAP:44,P80_INT_TRAP:53,\\",128,0,0,0
.stabs "UART_INT_TRAP:54,UART_TX_INT_TRAP:55,UART_RX_INT_TRAP:56,I2SL_INT_TRAP:58,I2SR_INT_TRAP:59,;",128,0,0,0
.stabs "_bitref:t14",128,0,0,0
.stabs "GREV_BIT_NEW:t36",128,0,0,0
.stabs "ClusterListItem:t37",128,0,0,0
.stabs "Record:t38",128,0,0,0
.stabs "BOOKNEWS:t39",128,0,0,0
.stabs "LASTBOOK:t40",128,0,0,0
.stabs "DWord:t11",128,0,0,0
.stabs "Word:t14",128,0,0,0
.stabs "Int32:t6",128,0,0,0
.stabs "Int16:t1",128,0,0,0
.stabs "Int8:t2",128,0,0,0
.stabs "Uint32:t11",128,0,0,0
.stabs "Uint16:t14",128,0,0,0
.stabs "Byte:t10",128,0,0,0
.stabs "Uchar:t10",128,0,0,0
.stabs "Uint8:t10",128,0,0,0
.stabs "WORD:t14",128,0,0,0
.stabs "ULONG:t11",128,0,0,0
.stabs "USHORT:t14",128,0,0,0
.stabs "Dword:t11",128,0,0,0
.stabs "UCHAR:t10",128,0,0,0
.stabs "FP64:t3",128,0,0,0
.stabs "FP32:t4",128,0,0,0
.stabs "INT32S:t6",128,0,0,0
.stabs "INT32U:t11",128,0,0,0
.stabs "INT16S:t1",128,0,0,0
.stabs "INT16U:t14",128,0,0,0
.stabs "INT8S:t9",128,0,0,0
.stabs "INT8U:t10",128,0,0,0
.stabs "BOOLEAN:t10",128,0,0,0
.stabs "Union16:t41",128,0,0,0
.stabs "Union32:t43",128,0,0,0
.stabs "Status_bool:t10",128,0,0,0
.stabs "Status:t10",128,0,0,0
.stabs "Bool:t10",128,0,0,0
.stabs "S32:t6",128,0,0,0
.stabs "S16:t8",128,0,0,0
.stabs "S8:t9",128,0,0,0
.stabs "U32:t11",128,0,0,0
.stabs "U16:t13",128,0,0,0
.stabs "U8:t10",128,0,0,0
.stabs "Float16:t4",128,0,0,0
.stabs ":t116=*117=f15",128,4,0,0
.stabs "tStorageBusyCallBackFunc:t116",128,0,0,0
.stabs "tFSDrvHandle:t67",128,0,0,0
.stabs "FS_ENTRY_INFO:t70",128,0,0,0
.stabs "FAT_CACHE:t71",128,0,0,0
.stabs "FSINFO:t51",128,0,0,0
.stabs "FCFILE:t47",128,0,0,0
.stabs "FILE_INFO:t74",128,0,0,0
.stabs "FS_ERR:t66",128,0,0,0
.stabs "wchar_t:t13",128,0,0,0
.stabs "size_t:t11",128,0,0,0
.stabs "ptrdiff_t:t1",128,0,0,0
.stabs "tSDKLoadCodeStatus:t78",128,0,0,0
.stabs "tKBLBSParseContentStatus:t79",128,0,0,0
.stabs "tKBLBSHeadInfo:t80",128,0,0,0
.stabs "tKBLBSParseHeadStatus:t81",128,0,0,0
.stabs "tIMA_INFO:t82",128,0,0,0
.stabs "tMp3SampleRateID:t83",128,0,0,0
.stabs "tMixer_Out:t84",128,0,0,0
.stabs "tMixer_Option:t85",128,0,0,0
.stabs ":t118=*119=f15",128,4,0,0
.stabs "tAUADC_BufNotify:t118",128,0,0,0
.stabs "tAUADC_In_Path:t86",128,0,0,0
.stabs "tAUADC_MIC_Gain:t87",128,0,0,0
.stabs "tAUADC_Input_Gain:t88",128,0,0,0
.stabs "tAUADC_SmapleRate:t89",128,0,0,0
.stabs "tAUADC_Err:t90",128,0,0,0
.stabs "tDAC_SampleRate:t91",128,0,0,0
.stabs "tDAC_Error:t92",128,0,0,0
.stabs "_STORAGE:t96",128,0,0,0
.stabs ":t120=*121=f15",128,4,0,0
.stabs "tSPIFBusyCallBackFunc:t120",128,0,0,0
.stabs "tSPI_Clock:t110",128,0,0,0
.stabs "SPIF_ERR:t111",128,0,0,0
.stabs "SDTL_ERR:t112",128,0,0,0
.stabs ":t122=*123=f15",128,4,0,0
.stabs "PFWAKEUP:t122",128,0,0,0
.stabs "tFEQ:t113",128,0,0,0
.stabs "tKBDM9_DTUNumber:t114",128,0,0,0
.stabs "tKBDM9_TrapNo:t115",128,0,0,0

.area _$USB_MassStorage_UGP_c$(ROM,REL)
.stabs "", 100, 0, 0,Letext
Letext:

; THE END
