del /Q Fw\SPI\ADPCM\output\*.*
del /Q Fw\SPI\dic\output\*.*
del /Q Fw\SPI\mp3\output\*.*
del /Q Fw\SPI\OID\output\*.*
del /Q Fw\SPI\OTP\output\*.*
del /Q Fw\SPI\PASTER\output\*.*
del /Q Fw\SPI\cab\output\*.*
del /Q Fw\SPI\RP\output\*.*
del /Q Fw\SPI\USB\output\*.*
del /Q Fw\SPI\Usb_Hid\output\*.*
del /Q Fw\SPI\wireless_oid\output\*.*
del /Q Fw\SPI\poweroff\output\*.*
del /Q Fw\SPI\upgrade\output\*.*
del /Q Fw\SPI\readbnl\output\*.*
del /Q Fw\UsbMassStoragev1.1\OutPut\*.*
del /Q Fw\MP3v316\Prj\OutPut\*.*
del /Q Fw\SPI\Story\OutPut\*.*
del /Q Fw\UpgBurnSPI\output\*.*
del /Q Fw\SPI\DIY\output\*.*
del /Q Fw\SPI\readOid\output\*.*