#ifndef _HT1382_H_
#define _HT1382_H_

//-----------------------------------------
#define MARK_READ				1
#define MARK_WRITE			 	0

///----define ht1382 register
#define ADDR_READ_BEGIN	 		0XD1
#define ADDR_WRITE_BEGIN		0XD0

//-----define ht1382 command
#define COMMAND_WRITE_SEC			0x80
#define COMMAND_READ_SEC			0x81
#define COMMAND_WRITE_MIN			0x82
#define COMMAND_READ_MIN			0x83
#define COMMAND_WRITE_HOURS			0x84
#define COMMAND_READ_HOURS			0x85
#define COMMAND_WRITE_DATE			0x86
#define COMMAND_READ_DATE			0x87
#define COMMAND_WRITE_MONTH			0x88
#define COMMAND_READ_MONTH			0x89
#define COMMAND_WRITE_DAY			0x8A
#define COMMAND_READ_DAY			0x8B
#define COMMAND_WRITE_YEAR			0x8C
#define COMMAND_READ_YEAD			0x8D
#define COMMAND_WRITE_ST_1			0x8E
#define COMMAND_READ_ST_1			0x8F
#define COMMAND_WRITE_ST_2			0x90
#define COMMAND_READ_ST_2			0x91
#define COMMAND_WRITE_INT			0x92
#define COMMAND_READ_INT			0x93
#define COMMAND_WRITE_ALARM_SEC		0x94
#define COMMAND_READ_ALARM_SEC		0x95
#define COMMAND_WRITE_ALARM_MIN		0x96
#define COMMAND_READ_ALARM_MIN		0x97
#define COMMAND_WRITE_ALARM_HOUR	0x98
#define COMMAND_READ_ALARM_HOUR		0x99
#define COMMAND_WRITE_ALARM_DATE	0x9A
#define COMMAND_READ_ALARM_DATE		0x9B
#define COMMAND_WRITE_ALARM_MONTH	0x9C
#define COMMAND_READ_ALARM_MONTH	0x9D
#define COMMAND_WRITE_ALARM_DAY		0x9E
#define COMMAND_READ_ALARM_DAY		0x9F
#define COMMAND_WRITE_DT			0xA0
#define COMMAND_READ_DT				0xA1
#define COMMAND_WRITE_USER_1		0xA2
#define COMMAND_READ_USER_1			0xA3
#define COMMAND_WRITE_USER_2		0xA4
#define COMMAND_READ_USER_2			0xA5
#define COMMAND_WRITE_USER_3		0xA6
#define COMMAND_READ_USER_3			0xA7
#define COMMAND_WRITE_USER_4		0xA8
#define COMMAND_READ_USER_4			0xA9




#endif   //_HT1382_H_