del /Q KB952\ap4\ap4\output\*.*
del /Q KB952\dic\dic\output\*.*
del /Q KB952\idle\idle\output\*.*
del /Q KB952\paster\paster\output\*.*
del /Q KB952\play\play\output\*.*
del /Q KB952\poweroff\poweroff\output\*.*
del /Q KB952\recorder\recorder\output\*.*
del /Q KB952\setting\setting\output\*.*
del /Q KB952\startup\startup\output\*.*
del /Q KB952\startup\boot\output\*.*
del /Q KB952\usb\usb\output\*.*
del /Q KB952\usbhid\usbhid\output\*.*
del /Q KB952\explorer\explorer\output\*.*
del /Q KB952\wireless\wireless\output\*.*
del /Q KB952\update\update\output\*.*
del /Q KB952\wireless\wireless\output\*.*
del /Q KB952\study\study\output\*.*
del /Q KB952\reread\reread\output\*.*
del /Q KB952\bluetooth\bluebooth\output\*.*
del /Q KB952\hid\usbhid\output\*.*
del /Q KB952\UpgBurnSPI\output\*.*
del /Q KB952\USB_MassStorage_Project\output\*.*

